package gogen

import (
	"fmt"

	"github.com/SpotlightGOV/pbflags/internal/codegen/contextutil"
	"google.golang.org/protobuf/compiler/protogen"
)

const pbflagsImport = "github.com/SpotlightGOV/pbflags/pbflags"

// generateDimsPackage generates a dims package with typed dimension
// constructors from the EvaluationContext proto message.
func generateDimsPackage(plugin *protogen.Plugin, ctx *contextutil.ContextDef, packagePrefix string) error {
	importPath := protogen.GoImportPath(packagePrefix + "/dims")
	g := plugin.NewGeneratedFile("dims/dims.go", importPath)
	p := g.P

	// Import qualifiers.
	pbflagsIdent := func(name string) protogen.GoIdent {
		return protogen.GoIdent{GoName: name, GoImportPath: pbflagsImport}
	}

	p("// Code generated by protoc-gen-pbflags. DO NOT EDIT.")
	p()
	p("package dims")
	p()

	for _, dim := range ctx.Dimensions {
		goName := toPascalCase(dim.Name)
		desc := dim.Description
		if desc == "" {
			desc = dim.Name + " dimension"
		}

		switch dim.Kind {
		case contextutil.DimensionString:
			p("// ", goName, " sets the ", dim.Name, " dimension (", desc, ").")
			p("func ", goName, "(v string) ", pbflagsIdent("Dimension"), " {")
			p("	return ", pbflagsIdent("StringDimension"), "(", fmt.Sprintf("%q", dim.Name), ", v)")
			p("}")
			p()

		case contextutil.DimensionBool:
			p("// ", goName, " sets the ", dim.Name, " dimension (", desc, ").")
			p("func ", goName, "(v bool) ", pbflagsIdent("Dimension"), " {")
			p("	return ", pbflagsIdent("BoolDimension"), "(", fmt.Sprintf("%q", dim.Name), ", v)")
			p("}")
			p()

		case contextutil.DimensionInt64:
			p("// ", goName, " sets the ", dim.Name, " dimension (", desc, ").")
			p("func ", goName, "(v int64) ", pbflagsIdent("Dimension"), " {")
			p("	return ", pbflagsIdent("Int64Dimension"), "(", fmt.Sprintf("%q", dim.Name), ", v)")
			p("}")
			p()

		case contextutil.DimensionEnum:
			// Import the generated enum type from the proto package.
			enumIdent := dim.ProtoField.Enum.GoIdent
			p("// ", goName, " sets the ", dim.Name, " dimension (", desc, ").")
			p("func ", goName, "(v ", enumIdent, ") ", pbflagsIdent("Dimension"), " {")
			p("	return ", pbflagsIdent("EnumDimension"), "(", fmt.Sprintf("%q", dim.Name), ", ", g.QualifiedGoIdent(protogen.GoIdent{GoName: "EnumNumber", GoImportPath: "google.golang.org/protobuf/reflect/protoreflect"}), "(v))")
			p("}")
			p()
		}
	}

	return nil
}
