package gogen

import "google.golang.org/protobuf/compiler/protogen"

// generateFlagMetaPackage generates a shared flagmeta package with the
// FlagDescriptor struct and FlagType enum used by per-feature FlagDescriptors
// slices.
func generateFlagMetaPackage(plugin *protogen.Plugin, packagePrefix string) error {
	importPath := protogen.GoImportPath(packagePrefix + "/flagmeta")
	g := plugin.NewGeneratedFile("flagmeta/flagmeta.go", importPath)
	p := g.P

	p("// Code generated by protoc-gen-pbflags. DO NOT EDIT.")
	p()
	p("package flagmeta")
	p()
	p("import \"log/slog\"")
	p()

	// Option / Config / WithLogger / Apply
	p("// Option configures a generated flag client.")
	p("type Option func(*Config)")
	p()
	p("// Config holds settings for a generated flag client.")
	p("type Config struct {")
	p("	Logger *slog.Logger")
	p("}")
	p()
	p("// WithLogger sets a custom logger for flag evaluation errors.")
	p("// By default, clients log via slog.Default().")
	p("func WithLogger(l *slog.Logger) Option {")
	p("	return func(c *Config) { c.Logger = l }")
	p("}")
	p()
	p("// Apply builds a Config from the given options, using slog.Default() when")
	p("// no logger is provided.")
	p("func Apply(opts ...Option) Config {")
	p("	cfg := Config{Logger: slog.Default()}")
	p("	for _, o := range opts {")
	p("		o(&cfg)")
	p("	}")
	p("	return cfg")
	p("}")
	p()

	p("// FlagType identifies the underlying scalar type of a flag.")
	p("type FlagType int")
	p()
	p("const (")
	p("	FlagTypeBool   FlagType = iota")
	p("	FlagTypeString")
	p("	FlagTypeInt64")
	p("	FlagTypeDouble")
	p(")")
	p()

	p("// String returns the Go type name for the flag type.")
	p("func (t FlagType) String() string {")
	p("	switch t {")
	p("	case FlagTypeBool:")
	p(`		return "bool"`)
	p("	case FlagTypeString:")
	p(`		return "string"`)
	p("	case FlagTypeInt64:")
	p(`		return "int64"`)
	p("	case FlagTypeDouble:")
	p(`		return "float64"`)
	p("	default:")
	p(`		return "unknown"`)
	p("	}")
	p("}")
	p()

	p("// FlagDescriptor provides structured metadata about a single flag.")
	p("type FlagDescriptor struct {")
	p(`	ID        string   // Flag ID (e.g., "notifications/1").`)
	p(`	FieldName string   // Proto field name (e.g., "email_enabled").`)
	p("	Type      FlagType // Underlying scalar type.")
	p("	IsList    bool     // True for repeated (list-valued) flags.")
	p()
	p("	// Compiled default value. Only the field matching Type (and IsList) is populated.")
	p("	DefaultBool    bool")
	p("	DefaultString  string")
	p("	DefaultInt64   int64")
	p("	DefaultDouble  float64")
	p("	DefaultBools   []bool")
	p("	DefaultStrings []string")
	p("	DefaultInt64s  []int64")
	p("	DefaultDoubles []float64")
	p("}")

	return nil
}

// flagMetaTypeName returns the flagmeta.FlagType constant name for a flag.
func flagMetaTypeName(fl flagInfo) string {
	baseType := fl.goType
	if fl.isList {
		// Strip "[]" prefix to get the scalar type.
		baseType = fl.goType[2:]
	}
	switch baseType {
	case "bool":
		return "flagmeta.FlagTypeBool"
	case "string":
		return "flagmeta.FlagTypeString"
	case "int64":
		return "flagmeta.FlagTypeInt64"
	case "float64":
		return "flagmeta.FlagTypeDouble"
	default:
		return "flagmeta.FlagTypeBool"
	}
}

// flagMetaDefaultField returns the FlagDescriptor field name for the default
// value of a flag (e.g., "DefaultBool", "DefaultStrings").
func flagMetaDefaultField(fl flagInfo) string {
	switch fl.goType {
	case "bool":
		return "DefaultBool"
	case "string":
		return "DefaultString"
	case "int64":
		return "DefaultInt64"
	case "float64":
		return "DefaultDouble"
	case "[]bool":
		return "DefaultBools"
	case "[]string":
		return "DefaultStrings"
	case "[]int64":
		return "DefaultInt64s"
	case "[]float64":
		return "DefaultDoubles"
	default:
		return "DefaultBool"
	}
}
