// Package gogen generates Go flag client code from feature proto definitions.
package gogen

import (
	"fmt"
	"math"
	"strings"

	"github.com/SpotlightGOV/pbflags/internal/codegen/layerutil"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/encoding/protowire"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// Generate produces Go flag client code for all feature messages in the plugin request.
func Generate(plugin *protogen.Plugin, packagePrefix string) error {
	layers, err := layerutil.DiscoverLayers(plugin)
	if err != nil {
		return err
	}

	if err := generateLayersPackage(plugin, layers, packagePrefix); err != nil {
		return fmt.Errorf("generating layers package: %w", err)
	}

	for _, f := range plugin.Files {
		if !f.Generate {
			continue
		}
		for _, msg := range f.Messages {
			feat := extractFeatureOptions(msg)
			if feat == nil {
				continue
			}
			if err := generateFeature(plugin, msg, feat, packagePrefix, layers); err != nil {
				return fmt.Errorf("generating %s: %w", feat.id, err)
			}
		}
	}
	return nil
}

type featureInfo struct {
	id          string
	description string
	owner       string
}

type flagInfo struct {
	goName      string
	fieldNumber int32
	goType      string
	getterName  string
	oneofType   string
	defaultVal  string
	hasDefault  bool
	isList      bool   // true for repeated (list-valued) flags
	layerName   string // empty = global; otherwise the lowercase layer name (e.g., "user", "entity")
}

const connectImport = "connectrpc.com/connect"

func generateFeature(plugin *protogen.Plugin, msg *protogen.Message, feat *featureInfo, packagePrefix string, layers *layerutil.LayerDef) error {
	flags, err := extractFlags(msg, layers)
	if err != nil {
		return err
	}
	if len(flags) == 0 {
		return nil
	}

	pkgName := strings.ToLower(feat.id) + "flags"
	outPath := pkgName + "/" + feat.id + "_flags.go"
	importPath := protogen.GoImportPath(packagePrefix + "/" + pkgName)
	pascalFeat := toPascalCase(feat.id)
	clientType := lowerFirst(pascalFeat) + "FlagsClient"

	flagsV1Import := packagePrefix + "/v1"
	flagsV1ConnectImport := packagePrefix + "/v1/pbflagsv1connect"
	layersImport := packagePrefix + "/layers"

	// Check if any flag uses a layer (needs layers import).
	hasLayerFlags := false
	for _, fl := range flags {
		if fl.layerName != "" {
			hasLayerFlags = true
			break
		}
	}

	g := plugin.NewGeneratedFile(outPath, importPath)
	p := g.P

	p("// Code generated by protoc-gen-pbflags. DO NOT EDIT.")
	p()
	p("package ", pkgName)
	p()
	p("import (")
	p(`	"context"`)
	p()
	p(`	"`, connectImport, `"`)
	p(`	pbflagsv1 "`, flagsV1Import, `"`)
	p(`	"`, flagsV1ConnectImport, `"`)
	if hasLayerFlags {
		p(`	"`, layersImport, `"`)
	}
	p(")")
	p()

	p("const FeatureID = ", fmt.Sprintf("%q", feat.id))
	p()

	p("// Flag ID constants. Format: feature_id/field_number.")
	p("const (")
	for _, fl := range flags {
		p("	", fl.goName, "ID = ", fmt.Sprintf("%q", fmt.Sprintf("%s/%d", feat.id, fl.fieldNumber)))
	}
	p(")")
	p()

	// Scalar defaults as constants.
	hasScalarDefaults := false
	for _, fl := range flags {
		if fl.hasDefault && !fl.isList {
			hasScalarDefaults = true
			break
		}
	}
	if hasScalarDefaults {
		p("// Compiled defaults from proto annotations.")
		p("const (")
		for _, fl := range flags {
			if fl.hasDefault && !fl.isList {
				p("	", fl.goName, "Default = ", fl.defaultVal)
			}
		}
		p(")")
		p()
	}

	// List defaults as functions (slices can't be constants).
	for _, fl := range flags {
		if fl.hasDefault && fl.isList {
			p("// ", fl.goName, "Default returns the compiled default for ", fl.goName, ".")
			p("func ", fl.goName, "Default() ", fl.goType, " {")
			p("	return ", fl.defaultVal)
			p("}")
			p()
		}
	}

	p("// ", pascalFeat, "Flags provides type-safe access to ", feat.id, " feature flags.")
	p("type ", pascalFeat, "Flags interface {")
	for _, fl := range flags {
		if fl.layerName != "" {
			p("	", fl.goName, "(ctx context.Context, ", layerParamName(fl.layerName), " layers.", layerTypeName(fl.layerName), ") ", fl.goType)
		} else {
			p("	", fl.goName, "(ctx context.Context) ", fl.goType)
		}
	}
	p()
	p("	// Status returns the evaluator's current health state.")
	p("	Status(ctx context.Context) pbflagsv1.EvaluatorStatus")
	p("}")
	p()

	p("// New", pascalFeat, "FlagsClient creates a client backed by a FlagEvaluator connection.")
	p("func New", pascalFeat, "FlagsClient(evaluator pbflagsv1connect.FlagEvaluatorServiceClient) ", pascalFeat, "Flags {")
	p("	return &", clientType, "{evaluator: evaluator}")
	p("}")
	p()

	p("type ", clientType, " struct {")
	p("	evaluator pbflagsv1connect.FlagEvaluatorServiceClient")
	p("}")
	p()

	for _, fl := range flags {
		if fl.layerName != "" {
			paramName := layerParamName(fl.layerName)
			p("func (c *", clientType, ") ", fl.goName, "(ctx context.Context, ", paramName, " layers.", layerTypeName(fl.layerName), ") ", fl.goType, " {")
			p("	resp, err := c.evaluator.Evaluate(ctx, connect.NewRequest(&pbflagsv1.EvaluateRequest{")
			p("		FlagId:   ", fl.goName, "ID,")
			p("		EntityId: ", paramName, ".String(),")
			p("	}))")
		} else {
			p("func (c *", clientType, ") ", fl.goName, "(ctx context.Context) ", fl.goType, " {")
			p("	resp, err := c.evaluator.Evaluate(ctx, connect.NewRequest(&pbflagsv1.EvaluateRequest{")
			p("		FlagId: ", fl.goName, "ID,")
			p("	}))")
		}
		p("	if err != nil {")
		emitReturnDefault(p, fl)
		p("	}")
		p("	if _, ok := resp.Msg.GetValue().GetValue().(*pbflagsv1.", fl.oneofType, "); !ok {")
		emitReturnDefault(p, fl)
		p("	}")
		if fl.isList {
			p("	return resp.Msg.GetValue().", fl.getterName, "().GetValues()")
		} else {
			p("	return resp.Msg.GetValue().", fl.getterName, "()")
		}
		p("}")
		p()
	}

	p("func (c *", clientType, ") Status(ctx context.Context) pbflagsv1.EvaluatorStatus {")
	p("	resp, err := c.evaluator.Health(ctx, connect.NewRequest(&pbflagsv1.HealthRequest{}))")
	p("	if err != nil {")
	p("		return pbflagsv1.EvaluatorStatus_EVALUATOR_STATUS_UNSPECIFIED")
	p("	}")
	p("	return resp.Msg.Status")
	p("}")
	p()

	// Generate Defaults() constructor and default implementation (null object pattern).
	defaultType := "default" + pascalFeat + "Flags"

	p("// Defaults returns a ", pascalFeat, "Flags that always returns the compiled")
	p("// default for every flag. Use this when no evaluator is available to avoid")
	p("// nil checks at call sites.")
	p("func Defaults() ", pascalFeat, "Flags {")
	p("	return ", defaultType, "{}")
	p("}")
	p()

	p("type ", defaultType, " struct{}")
	p()

	for _, fl := range flags {
		if fl.layerName != "" {
			p("func (", defaultType, ") ", fl.goName, "(_ context.Context, _ layers.", layerTypeName(fl.layerName), ") ", fl.goType, " {")
		} else {
			p("func (", defaultType, ") ", fl.goName, "(_ context.Context) ", fl.goType, " {")
		}
		emitReturnDefault(p, fl)
		p("}")
		p()
	}

	p("func (", defaultType, ") Status(_ context.Context) pbflagsv1.EvaluatorStatus {")
	p("	return pbflagsv1.EvaluatorStatus_EVALUATOR_STATUS_UNSPECIFIED")
	p("}")

	return nil
}

func extractFeatureOptions(msg *protogen.Message) *featureInfo {
	opts := msg.Desc.Options()
	if opts == nil {
		return nil
	}

	protoMsg := opts.(interface{ ProtoReflect() protoreflect.Message })
	rm := protoMsg.ProtoReflect()

	var feat *featureInfo
	rm.Range(func(fd protoreflect.FieldDescriptor, v protoreflect.Value) bool {
		if fd.Number() == 51000 && fd.IsExtension() {
			m := v.Message()
			info := &featureInfo{}
			m.Range(func(innerFd protoreflect.FieldDescriptor, innerV protoreflect.Value) bool {
				switch innerFd.Name() {
				case "id":
					info.id = innerV.String()
				case "description":
					info.description = innerV.String()
				case "owner":
					info.owner = innerV.String()
				}
				return true
			})
			if info.id != "" {
				feat = info
			}
			return false
		}
		return true
	})
	if feat != nil {
		return feat
	}

	unk := rm.GetUnknown()
	if len(unk) == 0 {
		return nil
	}
	return parseFeatureFromUnknown(unk)
}

func parseFeatureFromUnknown(b []byte) *featureInfo {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return nil
		}
		b = b[n:]
		if num == 51000 && typ == protowire.BytesType {
			data, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return nil
			}
			return parseFeatureMessage(data)
		}
		n = skipField(b, typ)
		if n < 0 {
			return nil
		}
		b = b[n:]
	}
	return nil
}

func parseFeatureMessage(b []byte) *featureInfo {
	info := &featureInfo{}
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return nil
		}
		b = b[n:]
		if typ != protowire.BytesType {
			n = skipField(b, typ)
			if n < 0 {
				return nil
			}
			b = b[n:]
			continue
		}
		data, n := protowire.ConsumeBytes(b)
		if n < 0 {
			return nil
		}
		b = b[n:]
		switch num {
		case 1:
			info.id = string(data)
		case 2:
			info.description = string(data)
		case 3:
			info.owner = string(data)
		}
	}
	if info.id == "" {
		return nil
	}
	return info
}

func extractFlags(msg *protogen.Message, layers *layerutil.LayerDef) ([]flagInfo, error) {
	var flags []flagInfo
	for _, field := range msg.Fields {
		fl, err := extractFlagFromField(field, layers)
		if err != nil {
			return nil, err
		}
		if fl != nil {
			flags = append(flags, *fl)
		}
	}
	return flags, nil
}

func extractFlagFromField(field *protogen.Field, layers *layerutil.LayerDef) (*flagInfo, error) {
	opts := field.Desc.Options()
	if opts == nil {
		return nil, nil
	}

	protoMsg := opts.(interface{ ProtoReflect() protoreflect.Message })
	rm := protoMsg.ProtoReflect()

	var found bool
	var layerStr string
	var defaultVal string
	var hasDefault bool

	rm.Range(func(fd protoreflect.FieldDescriptor, v protoreflect.Value) bool {
		if fd.Number() == 51001 && fd.IsExtension() {
			found = true
			m := v.Message()
			m.Range(func(innerFd protoreflect.FieldDescriptor, innerV protoreflect.Value) bool {
				switch innerFd.Name() {
				case "layer":
					layerStr = innerV.String()
				case "default":
					defaultVal, hasDefault = extractDefaultReflect(innerV.Message())
				}
				return true
			})
			return false
		}
		return true
	})

	if !found {
		unk := rm.GetUnknown()
		if len(unk) == 0 {
			return nil, nil
		}
		found, layerStr, defaultVal, hasDefault = parseFlagFromUnknown(unk, field.Desc.Kind())
		if !found {
			return nil, nil
		}
	}

	// Validate the layer against the discovered enum.
	var resolvedLayerName string
	if layerStr != "" {
		lv, ok := layers.ResolveLayer(layerStr)
		if !ok {
			return nil, fmt.Errorf("flag %s.%s: layer %q does not match any value in the %s enum",
				field.Parent.Desc.Name(), field.Desc.Name(), layerStr, layers.EnumName)
		}
		if !lv.IsGlobal {
			resolvedLayerName = lv.LayerName
		}
	}

	goName := toPascalCase(string(field.Desc.Name()))
	isList := field.Desc.IsList()
	goType, getterName, oneofType := goTypeInfo(field.Desc.Kind(), isList)

	return &flagInfo{
		goName:      goName,
		fieldNumber: int32(field.Desc.Number()),
		goType:      goType,
		getterName:  getterName,
		oneofType:   oneofType,
		defaultVal:  defaultVal,
		hasDefault:  hasDefault,
		isList:      isList,
		layerName:   resolvedLayerName,
	}, nil
}

func extractDefaultReflect(defMsg protoreflect.Message) (string, bool) {
	var val string
	var ok bool

	defMsg.Range(func(fd protoreflect.FieldDescriptor, v protoreflect.Value) bool {
		switch fd.Name() {
		case "bool_list_value", "string_list_value", "int64_list_value", "double_list_value":
			val, ok = extractListDefaultReflect(fd.Name(), v.Message())
			return false
		}
		wrapperMsg := v.Message()
		wrapperMsg.Range(func(wfd protoreflect.FieldDescriptor, wv protoreflect.Value) bool {
			if wfd.Name() != "value" {
				return true
			}
			switch fd.Name() {
			case "bool_value":
				ok = true
				if wv.Bool() {
					val = "true"
				} else {
					val = "false"
				}
			case "string_value":
				ok = true
				val = fmt.Sprintf("%q", wv.String())
			case "int64_value":
				ok = true
				val = fmt.Sprintf("int64(%d)", wv.Int())
			case "double_value":
				ok = true
				val = fmt.Sprintf("float64(%v)", wv.Float())
			}
			return false
		})
		return false
	})

	return val, ok
}

func extractListDefaultReflect(fieldName protoreflect.Name, listMsg protoreflect.Message) (string, bool) {
	valField := listMsg.Descriptor().Fields().ByNumber(1) // repeated values = 1
	if valField == nil {
		return "", false
	}
	list := listMsg.Get(valField).List()
	var items []string
	for i := 0; i < list.Len(); i++ {
		switch fieldName {
		case "bool_list_value":
			if list.Get(i).Bool() {
				items = append(items, "true")
			} else {
				items = append(items, "false")
			}
		case "string_list_value":
			items = append(items, fmt.Sprintf("%q", list.Get(i).String()))
		case "int64_list_value":
			items = append(items, fmt.Sprintf("int64(%d)", list.Get(i).Int()))
		case "double_list_value":
			items = append(items, fmt.Sprintf("float64(%v)", list.Get(i).Float()))
		}
	}
	switch fieldName {
	case "bool_list_value":
		return "[]bool{" + strings.Join(items, ", ") + "}", true
	case "string_list_value":
		return "[]string{" + strings.Join(items, ", ") + "}", true
	case "int64_list_value":
		return "[]int64{" + strings.Join(items, ", ") + "}", true
	case "double_list_value":
		return "[]float64{" + strings.Join(items, ", ") + "}", true
	}
	return "", false
}

func parseFlagFromUnknown(b []byte, fieldKind protoreflect.Kind) (found bool, layerStr string, defaultVal string, hasDefault bool) {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return
		}
		b = b[n:]
		if num == 51001 && typ == protowire.BytesType {
			data, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return
			}
			found = true
			layerStr, defaultVal, hasDefault = parseFlagOptionsMessage(data, fieldKind)
			return
		}
		n = skipField(b, typ)
		if n < 0 {
			return
		}
		b = b[n:]
	}
	return
}

func parseFlagOptionsMessage(b []byte, fieldKind protoreflect.Kind) (layerStr string, defaultVal string, hasDefault bool) {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return
		}
		b = b[n:]
		switch num {
		case 2:
			if typ == protowire.BytesType {
				data, n := protowire.ConsumeBytes(b)
				if n < 0 {
					return
				}
				b = b[n:]
				defaultVal, hasDefault = parseFlagDefault(data, fieldKind)
				continue
			}
		case 5: // string layer field
			if typ == protowire.BytesType {
				data, n := protowire.ConsumeBytes(b)
				if n < 0 {
					return
				}
				b = b[n:]
				layerStr = string(data)
				continue
			}
		}
		n = skipField(b, typ)
		if n < 0 {
			return
		}
		b = b[n:]
	}
	return
}

func parseFlagDefault(b []byte, fieldKind protoreflect.Kind) (string, bool) {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return "", false
		}
		b = b[n:]
		if typ == protowire.BytesType {
			data, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return "", false
			}
			b = b[n:]
			switch num {
			case 1:
				return parseBoolWrapper(data)
			case 2:
				return parseStringWrapper(data)
			case 3:
				return parseInt64Wrapper(data)
			case 4:
				return parseDoubleWrapper(data)
			case 5:
				return parseBoolListMessage(data)
			case 6:
				return parseStringListMessage(data)
			case 7:
				return parseInt64ListMessage(data)
			case 8:
				return parseDoubleListMessage(data)
			}
			continue
		}
		n = skipField(b, typ)
		if n < 0 {
			return "", false
		}
		b = b[n:]
	}
	return "", false
}

func parseBoolListMessage(b []byte) (string, bool) {
	var items []string
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			break
		}
		b = b[n:]
		if num == 1 && typ == protowire.VarintType {
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				break
			}
			b = b[n:]
			if v != 0 {
				items = append(items, "true")
			} else {
				items = append(items, "false")
			}
			continue
		}
		n = skipField(b, typ)
		if n < 0 {
			break
		}
		b = b[n:]
	}
	return "[]bool{" + strings.Join(items, ", ") + "}", true
}

func parseStringListMessage(b []byte) (string, bool) {
	var items []string
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			break
		}
		b = b[n:]
		if num == 1 && typ == protowire.BytesType {
			data, n := protowire.ConsumeBytes(b)
			if n < 0 {
				break
			}
			b = b[n:]
			items = append(items, fmt.Sprintf("%q", string(data)))
			continue
		}
		n = skipField(b, typ)
		if n < 0 {
			break
		}
		b = b[n:]
	}
	return "[]string{" + strings.Join(items, ", ") + "}", true
}

func parseInt64ListMessage(b []byte) (string, bool) {
	var items []string
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			break
		}
		b = b[n:]
		if num == 1 && typ == protowire.VarintType {
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				break
			}
			b = b[n:]
			items = append(items, fmt.Sprintf("int64(%d)", int64(v)))
			continue
		}
		n = skipField(b, typ)
		if n < 0 {
			break
		}
		b = b[n:]
	}
	return "[]int64{" + strings.Join(items, ", ") + "}", true
}

func parseDoubleListMessage(b []byte) (string, bool) {
	var items []string
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			break
		}
		b = b[n:]
		if num == 1 && typ == protowire.Fixed64Type {
			v, n := protowire.ConsumeFixed64(b)
			if n < 0 {
				break
			}
			b = b[n:]
			items = append(items, fmt.Sprintf("float64(%v)", math.Float64frombits(v)))
			continue
		}
		n = skipField(b, typ)
		if n < 0 {
			break
		}
		b = b[n:]
	}
	return "[]float64{" + strings.Join(items, ", ") + "}", true
}

func parseBoolWrapper(b []byte) (string, bool) {
	val := false
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return "", false
		}
		b = b[n:]
		if num == 1 && typ == protowire.VarintType {
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				return "", false
			}
			b = b[n:]
			val = v != 0
			continue
		}
		n = skipField(b, typ)
		if n < 0 {
			return "", false
		}
		b = b[n:]
	}
	if val {
		return "true", true
	}
	return "false", true
}

func parseStringWrapper(b []byte) (string, bool) {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return "", false
		}
		b = b[n:]
		if num == 1 && typ == protowire.BytesType {
			data, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return "", false
			}
			return fmt.Sprintf("%q", string(data)), true
		}
		n = skipField(b, typ)
		if n < 0 {
			return "", false
		}
		b = b[n:]
	}
	return `""`, true
}

func parseInt64Wrapper(b []byte) (string, bool) {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return "", false
		}
		b = b[n:]
		if num == 1 && typ == protowire.VarintType {
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				return "", false
			}
			return fmt.Sprintf("int64(%d)", int64(v)), true
		}
		n = skipField(b, typ)
		if n < 0 {
			return "", false
		}
		b = b[n:]
	}
	return "int64(0)", true
}

func parseDoubleWrapper(b []byte) (string, bool) {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return "", false
		}
		b = b[n:]
		if num == 1 && typ == protowire.Fixed64Type {
			v, n := protowire.ConsumeFixed64(b)
			if n < 0 {
				return "", false
			}
			return fmt.Sprintf("float64(%v)", math.Float64frombits(v)), true
		}
		n = skipField(b, typ)
		if n < 0 {
			return "", false
		}
		b = b[n:]
	}
	return "float64(0)", true
}

func skipField(b []byte, typ protowire.Type) int {
	switch typ {
	case protowire.VarintType:
		_, n := protowire.ConsumeVarint(b)
		return n
	case protowire.Fixed32Type:
		_, n := protowire.ConsumeFixed32(b)
		return n
	case protowire.Fixed64Type:
		_, n := protowire.ConsumeFixed64(b)
		return n
	case protowire.BytesType:
		_, n := protowire.ConsumeBytes(b)
		return n
	default:
		return -1
	}
}

// emitReturnDefault emits a return statement for a flag's default value.
func emitReturnDefault(p func(...interface{}), fl flagInfo) {
	if fl.hasDefault {
		if fl.isList {
			p("	return ", fl.goName, "Default()")
		} else {
			p("	return ", fl.goName, "Default")
		}
	} else if fl.isList {
		p("	return nil")
	} else {
		p("	var zero ", fl.goType)
		p("	return zero")
	}
}

func goTypeInfo(kind protoreflect.Kind, isList bool) (goType, getterName, oneofType string) {
	if isList {
		switch kind {
		case protoreflect.BoolKind:
			return "[]bool", "GetBoolListValue", "FlagValue_BoolListValue"
		case protoreflect.StringKind:
			return "[]string", "GetStringListValue", "FlagValue_StringListValue"
		case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
			return "[]int64", "GetInt64ListValue", "FlagValue_Int64ListValue"
		case protoreflect.DoubleKind:
			return "[]float64", "GetDoubleListValue", "FlagValue_DoubleListValue"
		default:
			return "[]interface{}", "GetBoolListValue", "FlagValue_BoolListValue"
		}
	}
	switch kind {
	case protoreflect.BoolKind:
		return "bool", "GetBoolValue", "FlagValue_BoolValue"
	case protoreflect.StringKind:
		return "string", "GetStringValue", "FlagValue_StringValue"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return "int64", "GetInt64Value", "FlagValue_Int64Value"
	case protoreflect.DoubleKind:
		return "float64", "GetDoubleValue", "FlagValue_DoubleValue"
	default:
		return "interface{}", "GetBoolValue", "FlagValue_BoolValue"
	}
}

func toPascalCase(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

func lowerFirst(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}
