package gogen

import (
	"strings"
	"unicode"

	"github.com/SpotlightGOV/pbflags/internal/codegen/layerutil"
	"google.golang.org/protobuf/compiler/protogen"
)

// generateLayersPackage generates a shared layers package with typed ID
// wrappers for each non-global layer value.
func generateLayersPackage(plugin *protogen.Plugin, layers *layerutil.LayerDef, packagePrefix string) error {
	importPath := protogen.GoImportPath(packagePrefix + "/layers")
	g := plugin.NewGeneratedFile("layers/layers.go", importPath)
	p := g.P

	p("// Code generated by protoc-gen-pbflags. DO NOT EDIT.")
	p()
	p("package layers")
	p()

	// Collect non-global layers.
	var nonGlobal []layerutil.LayerValue
	for _, lv := range layers.Values {
		if !lv.IsGlobal {
			nonGlobal = append(nonGlobal, lv)
		}
	}

	if len(nonGlobal) == 0 {
		p("// No non-global layers defined.")
		return nil
	}

	for _, lv := range nonGlobal {
		typeName := toPascalCase(strings.ToLower(lv.StrippedName)) + "ID"
		ctorName := toPascalCase(strings.ToLower(lv.StrippedName))
		paramName := lowerFirst(toPascalCase(strings.ToLower(lv.StrippedName)))

		p("// ", typeName, " identifies ", addArticle(strings.ToLower(lv.StrippedName)), " for layer-scoped flag evaluation.")
		p("// The zero value evaluates global state.")
		p("type ", typeName, " struct{ v string }")
		p()
		p("// ", ctorName, " creates a ", typeName, " for the given identifier.")
		p("func ", ctorName, "(", paramName, " string) ", typeName, " { return ", typeName, "{v: ", paramName, "} }")
		p()
		p("// String returns the underlying identifier.")
		p("func (id ", typeName, ") String() string { return id.v }")
		p()
	}

	return nil
}

// addArticle adds "a" or "an" before a word.
func addArticle(word string) string {
	if len(word) == 0 {
		return word
	}
	first := unicode.ToLower(rune(word[0]))
	if first == 'a' || first == 'e' || first == 'i' || first == 'o' {
		return "an " + word
	}
	return "a " + word
}

// layerTypeName returns the Go type name for a layer (e.g., "entity" -> "EntityID").
func layerTypeName(layerName string) string {
	return toPascalCase(layerName) + "ID"
}

// layerParamName returns the Go parameter name for a layer (e.g., "entity" -> "entity").
func layerParamName(layerName string) string {
	return lowerFirst(toPascalCase(layerName))
}
