package gogen

import (
	"fmt"
	"strings"

	"github.com/SpotlightGOV/pbflags/internal/codegen/contextutil"
	"google.golang.org/protobuf/compiler/protogen"
)

// generateScopesPackage generates per-scope *Features types in the dims package.
// Each scope gets a FooFeatures struct with a constructor requiring its dimensions,
// and accessor methods for each feature that lists the scope. Duck-typed interfaces
// (HasXxx) are generated per feature.
func generateScopesPackage(
	plugin *protogen.Plugin,
	ctxDef *contextutil.ContextDef,
	scopes []contextutil.ScopeDef,
	features []*featureInfo,
	packagePrefix string,
) error {
	importPath := protogen.GoImportPath(packagePrefix + "/dims")
	g := plugin.NewGeneratedFile("dims/scopes.go", importPath)
	p := g.P

	// Build dimension lookup.
	dimByName := map[string]contextutil.DimensionDef{}
	for _, d := range ctxDef.Dimensions {
		dimByName[d.Name] = d
	}

	// Identify globally required dimensions (present in every scope implicitly).
	var globalDims []contextutil.DimensionDef
	for _, d := range ctxDef.Dimensions {
		if d.IsRequired() {
			globalDims = append(globalDims, d)
		}
	}

	// Build feature scope membership: featureID → set of scope names.
	featureScopeSet := map[string]map[string]bool{}
	for _, f := range features {
		featureScopeSet[f.id] = map[string]bool{}
		for _, s := range f.scopes {
			featureScopeSet[f.id][s] = true
		}
	}

	p("// Code generated by protoc-gen-pbflags. DO NOT EDIT.")
	p()
	p("package dims")
	p()

	// We use g.QualifiedGoIdent for imports so we don't need to emit an
	// import block manually — protogen handles it. But we do need to force
	// the "context" import since it's a stdlib package used by all scopes.
	contextIdent := protogen.GoIdent{GoName: "Context", GoImportPath: "context"}
	pbflagsIdent := func(name string) protogen.GoIdent {
		return protogen.GoIdent{GoName: name, GoImportPath: pbflagsImport}
	}

	// Force feature package imports and build alias map.
	featureImports := map[string]protogen.GoImportPath{} // featureID → import path
	for _, f := range features {
		if len(f.scopes) == 0 {
			continue
		}
		pkgName := strings.ToLower(f.id) + "flags"
		featureImports[f.id] = protogen.GoImportPath(packagePrefix + "/" + pkgName)
	}

	// Generate duck-typed interfaces per feature.
	for _, f := range features {
		if len(f.scopes) == 0 {
			continue
		}
		pascal := toPascalCase(f.id)
		featureIdent := protogen.GoIdent{GoName: pascal + "Flags", GoImportPath: featureImports[f.id]}
		p("// Has", pascal, " is a duck-typed interface for scopes that provide ", f.id, " flags.")
		p("type Has", pascal, " interface {")
		p("	", pascal, "() ", g.QualifiedGoIdent(featureIdent))
		p("}")
		p()
	}

	// Generate per-scope types.
	for _, scope := range scopes {
		scopePascal := toPascalCase(scope.Name)
		structName := scopePascal + "Features"

		// Collect all dimensions for this scope (global required + scope-specific).
		var scopeDims []contextutil.DimensionDef
		scopeDims = append(scopeDims, globalDims...)
		for _, dimName := range scope.Dimensions {
			if d, ok := dimByName[dimName]; ok {
				scopeDims = append(scopeDims, d)
			}
		}

		// Collect features available in this scope.
		var scopeFeatures []*featureInfo
		for _, f := range features {
			if featureScopeSet[f.id][scope.Name] {
				scopeFeatures = append(scopeFeatures, f)
			}
		}
		if len(scopeFeatures) == 0 {
			continue
		}

		// Build constructor parameters and struct fields with correct types.
		type dimField struct {
			goFieldName string
			goType      string // rendered Go type (may be qualified)
			dim         contextutil.DimensionDef
		}
		var fields []dimField
		var params []string
		params = append(params, fmt.Sprintf("eval %s", g.QualifiedGoIdent(pbflagsIdent("Evaluator"))))

		for _, d := range scopeDims {
			goName := lowerFirst(toPascalCase(d.Name))
			var goType string
			switch d.Kind {
			case contextutil.DimensionEnum:
				goType = g.QualifiedGoIdent(d.ProtoField.Enum.GoIdent)
			case contextutil.DimensionBool:
				goType = "bool"
			case contextutil.DimensionInt64:
				goType = "int64"
			default:
				goType = "string"
			}
			fields = append(fields, dimField{goFieldName: goName, goType: goType, dim: d})
			params = append(params, goName+" "+goType)
		}

		// Struct definition — includes cached feature clients (lazy-initialized).
		p("// ", structName, " provides feature flag access for the ", scope.Name, " evaluation scope.")
		p("type ", structName, " struct {")
		p("	eval ", g.QualifiedGoIdent(pbflagsIdent("Evaluator")))
		for _, f := range fields {
			p("	", f.goFieldName, " ", f.goType)
		}
		// Cached feature clients (populated on first access).
		for _, feat := range scopeFeatures {
			featureIdent := protogen.GoIdent{GoName: toPascalCase(feat.id) + "Flags", GoImportPath: featureImports[feat.id]}
			p("	cached", toPascalCase(feat.id), " ", g.QualifiedGoIdent(featureIdent))
		}
		p("}")
		p()

		// Constructor.
		p("// New", structName, " creates a ", structName, " with the given evaluator and dimensions.")
		p("func New", structName, "(", strings.Join(params, ", "), ") *", structName, " {")
		p("	return &", structName, "{")
		p("		eval: eval,")
		for _, f := range fields {
			p("		", f.goFieldName, ": ", f.goFieldName, ",")
		}
		p("	}")
		p("}")
		p()

		// ContextWith / From helpers.
		p("type ", lowerFirst(structName), "Key struct{}")
		p()
		p("// ContextWith", structName, " stores the features in a ", g.QualifiedGoIdent(contextIdent), ".")
		p("func ContextWith", structName, "(ctx ", g.QualifiedGoIdent(contextIdent), ", f *", structName, ") ", g.QualifiedGoIdent(contextIdent), " {")
		p("	return context.WithValue(ctx, ", lowerFirst(structName), "Key{}, f)")
		p("}")
		p()
		p("// ", structName, "From retrieves the features from a ", g.QualifiedGoIdent(contextIdent), ".")
		p("func ", structName, "From(ctx ", g.QualifiedGoIdent(contextIdent), ") *", structName, " {")
		p("	v, _ := ctx.Value(", lowerFirst(structName), "Key{}).(*", structName, ")")
		p("	return v")
		p("}")
		p()

		// Feature accessor methods (cached — created on first call).
		for _, feat := range scopeFeatures {
			pascal := toPascalCase(feat.id)
			featureIdent := protogen.GoIdent{GoName: pascal + "Flags", GoImportPath: featureImports[feat.id]}
			cachedField := "cached" + pascal

			p("// ", pascal, " returns a ", feat.id, " flags client scoped to this evaluation context.")
			p("func (f *", structName, ") ", pascal, "() ", g.QualifiedGoIdent(featureIdent), " {")
			p("	if f.", cachedField, " == nil {")
			p("		eval := f.eval")
			for _, df := range fields {
				dimFunc := toPascalCase(df.dim.Name)
				p("		eval = eval.With(", dimFunc, "(f.", df.goFieldName, "))")
			}
			newIdent := protogen.GoIdent{GoName: "New", GoImportPath: featureImports[feat.id]}
			p("		f.", cachedField, " = ", g.QualifiedGoIdent(newIdent), "(eval)")
			p("	}")
			p("	return f.", cachedField)
			p("}")
			p()
		}
	}

	return nil
}
