package gogen

import (
	"fmt"
	"strings"

	"github.com/SpotlightGOV/pbflags/internal/codegen/contextutil"
	"google.golang.org/protobuf/compiler/protogen"
)

// generateScopesPackage generates per-scope *Features types in the dims package.
// Each scope gets a FooFeatures struct with a constructor requiring its dimensions,
// and accessor methods for each feature that lists the scope. Duck-typed interfaces
// (HasXxx) are generated per feature.
func generateScopesPackage(
	plugin *protogen.Plugin,
	ctxDef *contextutil.ContextDef,
	scopes []contextutil.ScopeDef,
	features []*featureInfo,
	packagePrefix string,
) error {
	importPath := protogen.GoImportPath(packagePrefix + "/dims")
	g := plugin.NewGeneratedFile("dims/scopes.go", importPath)
	p := g.P

	// Build dimension lookup.
	dimByName := map[string]contextutil.DimensionDef{}
	for _, d := range ctxDef.Dimensions {
		dimByName[d.Name] = d
	}

	// Identify globally required dimensions (present in every scope implicitly).
	var globalDims []contextutil.DimensionDef
	for _, d := range ctxDef.Dimensions {
		if d.IsRequired() {
			globalDims = append(globalDims, d)
		}
	}

	// Build feature scope membership: featureID → set of scope names.
	featureScopeSet := map[string]map[string]bool{}
	for _, f := range features {
		featureScopeSet[f.id] = map[string]bool{}
		for _, s := range f.scopes {
			featureScopeSet[f.id][s] = true
		}
	}

	p("// Code generated by protoc-gen-pbflags. DO NOT EDIT.")
	p()
	p("package dims")
	p()
	p("import (")
	p(`	"context"`)
	p()
	p(`	"`, pbflagsImport, `"`)

	// Import feature packages.
	featureImports := map[string]string{} // featureID → import alias
	for _, f := range features {
		if len(f.scopes) == 0 {
			continue
		}
		pkgName := strings.ToLower(f.id) + "flags"
		alias := pkgName
		featureImports[f.id] = alias
		p(fmt.Sprintf("	%s %q", alias, packagePrefix+"/"+pkgName))
	}
	p(")")
	p()

	// Generate duck-typed interfaces per feature.
	for _, f := range features {
		if len(f.scopes) == 0 {
			continue
		}
		pascal := toPascalCase(f.id)
		alias := featureImports[f.id]
		p("// Has", pascal, " is a duck-typed interface for scopes that provide ", f.id, " flags.")
		p("type Has", pascal, " interface {")
		p("	", pascal, "() ", alias, ".", pascal, "Flags")
		p("}")
		p()
	}

	// Generate per-scope types.
	for _, scope := range scopes {
		scopePascal := toPascalCase(scope.Name)
		structName := scopePascal + "Features"

		// Collect all dimensions for this scope (global required + scope-specific).
		var scopeDims []contextutil.DimensionDef
		scopeDims = append(scopeDims, globalDims...)
		for _, dimName := range scope.Dimensions {
			if d, ok := dimByName[dimName]; ok {
				scopeDims = append(scopeDims, d)
			}
		}

		// Collect features available in this scope.
		var scopeFeatures []*featureInfo
		for _, f := range features {
			if featureScopeSet[f.id][scope.Name] {
				scopeFeatures = append(scopeFeatures, f)
			}
		}
		if len(scopeFeatures) == 0 {
			continue
		}

		// Constructor parameters: evaluator + scope dimensions.
		var params []string
		var fieldDefs []string
		params = append(params, "eval pbflags.Evaluator")
		for _, d := range scopeDims {
			goName := lowerFirst(toPascalCase(d.Name))
			goType := dimGoType(d.Kind)
			params = append(params, goName+" "+goType)
			fieldDefs = append(fieldDefs, fmt.Sprintf("%s %s", goName, goType))
		}

		// Struct definition.
		p("// ", structName, " provides feature flag access for the ", scope.Name, " evaluation scope.")
		p("type ", structName, " struct {")
		p("	eval pbflags.Evaluator")
		for _, fd := range fieldDefs {
			p("	", fd)
		}
		p("}")
		p()

		// Constructor.
		p("// New", structName, " creates a ", structName, " with the given evaluator and dimensions.")
		p("func New", structName, "(", strings.Join(params, ", "), ") *", structName, " {")
		p("	return &", structName, "{")
		p("		eval: eval,")
		for _, d := range scopeDims {
			goName := lowerFirst(toPascalCase(d.Name))
			p("		", goName, ": ", goName, ",")
		}
		p("	}")
		p("}")
		p()

		// ContextWith helper to store in context.Context.
		p("// key type for context storage.")
		p("type ", lowerFirst(structName), "Key struct{}")
		p()
		p("// ContextWith", structName, " stores the features in a context.Context.")
		p("func ContextWith", structName, "(ctx context.Context, f *", structName, ") context.Context {")
		p("	return context.WithValue(ctx, ", lowerFirst(structName), "Key{}, f)")
		p("}")
		p()
		p("// ", structName, "From retrieves the features from a context.Context.")
		p("func ", structName, "From(ctx context.Context) *", structName, " {")
		p("	v, _ := ctx.Value(", lowerFirst(structName), "Key{}).(*", structName, ")")
		p("	return v")
		p("}")
		p()

		// Feature accessor methods.
		for _, f := range scopeFeatures {
			pascal := toPascalCase(f.id)
			alias := featureImports[f.id]

			// Build the evaluator with dimensions.
			p("// ", pascal, " returns a ", f.id, " flags client scoped to this evaluation context.")
			p("func (f *", structName, ") ", pascal, "() ", alias, ".", pascal, "Flags {")
			p("	eval := f.eval")
			for _, d := range scopeDims {
				goName := lowerFirst(toPascalCase(d.Name))
				dimFunc := toPascalCase(d.Name)
				p("	eval = eval.With(", dimFunc, "(f.", goName, "))")
			}
			p("	return ", alias, ".New(eval)")
			p("}")
			p()
		}
	}

	return nil
}

// dimGoType returns the Go type for a dimension kind (for constructor parameters).
func dimGoType(kind contextutil.DimensionKind) string {
	switch kind {
	case contextutil.DimensionString:
		return "string"
	case contextutil.DimensionBool:
		return "bool"
	case contextutil.DimensionInt64:
		return "int64"
	default:
		return "string"
	}
}
