// Code generated by protoc-gen-pbflags. DO NOT EDIT.
package org.spotlightgov.pbflags.generated.layers;

/** Typed layer ID for the {@code entity} dimension. */
public final class EntityID {
  private final String value;
  private EntityID(String value) { this.value = value; }
  public static EntityID of(String id) { return new EntityID(id); }
  public static EntityID global() { return new EntityID(""); }
  public String value() { return value; }
  @Override public String toString() { return value; }
}
