// Code generated by protoc-gen-pbflags. DO NOT EDIT.
package org.spotlightgov.pbflags.generated.layers;

/** Typed layer ID for the {@code user} dimension. */
public final class UserID {
  private final String value;
  private UserID(String value) { this.value = value; }
  public static UserID of(String id) { return new UserID(id); }
  public static UserID global() { return new UserID(""); }
  public String value() { return value; }
  @Override public String toString() { return value; }
}
