// Package javagen generates Java flag client code from feature proto definitions.
package javagen

import (
	"fmt"
	"math"
	"path/filepath"
	"strings"

	"github.com/SpotlightGOV/pbflags/internal/codegen/contextutil"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/encoding/protowire"
	"google.golang.org/protobuf/reflect/protoreflect"
)

type featureEntry struct {
	feat     *featureInfo
	flags    []flagInfo
	msg      *protogen.Message
	protoSrc *protogen.File
}

// Generate produces Java flag client code for all feature messages.
// If dagger is true, generates a Dagger @Module and adds @Inject/@Singleton to impls.
func Generate(plugin *protogen.Plugin, javaPackage string, dagger ...bool) error {
	emitDagger := len(dagger) > 0 && dagger[0]
	_ = emitDagger // used below

	ctxDef, err := contextutil.DiscoverContext(plugin)
	if err != nil {
		return fmt.Errorf("discovering evaluation context: %w", err)
	}
	if ctxDef != nil {
		if err := generateDimensionsClass(plugin, ctxDef, javaPackage); err != nil {
			return fmt.Errorf("generating Dimensions class: %w", err)
		}
	}

	// Check for case-insensitive outer class name collisions early, before
	// generating any files.
	var genFiles []*protogen.File
	for _, f := range plugin.Files {
		if f.Generate {
			genFiles = append(genFiles, f)
		}
	}
	if err := checkOuterClassCaseCollisions(genFiles); err != nil {
		return err
	}

	var features []featureEntry
	for _, f := range plugin.Files {
		if !f.Generate {
			continue
		}
		for _, msg := range f.Messages {
			feat := extractFeatureOptions(msg)
			if feat == nil {
				continue
			}
			flags, err := extractFlags(msg)
			if err != nil {
				return err
			}
			if len(flags) == 0 {
				continue
			}
			features = append(features, featureEntry{feat: feat, flags: flags, msg: msg, protoSrc: f})
		}
	}
	if len(features) == 0 {
		return nil
	}

	pkgDir := strings.ReplaceAll(javaPackage, ".", "/")

	for _, entry := range features {
		if err := generateInterface(plugin, entry.feat, entry.flags, javaPackage, pkgDir); err != nil {
			return fmt.Errorf("generating interface for %s: %w", entry.feat.id, err)
		}
		if err := generateImpl(plugin, entry.feat, entry.flags, javaPackage, pkgDir, emitDagger); err != nil {
			return fmt.Errorf("generating impl for %s: %w", entry.feat.id, err)
		}
		if err := generateTestImpl(plugin, entry.feat, entry.flags, javaPackage, pkgDir); err != nil {
			return fmt.Errorf("generating test impl for %s: %w", entry.feat.id, err)
		}
	}

	if emitDagger {
		if err := generateDaggerModule(plugin, features, javaPackage, pkgDir); err != nil {
			return fmt.Errorf("generating Dagger module: %w", err)
		}
		if err := generateScopedEvaluatorModule(plugin, javaPackage, pkgDir); err != nil {
			return fmt.Errorf("generating scoped evaluator module: %w", err)
		}
	}

	if err := generateDescriptorProvider(plugin, features, javaPackage, pkgDir); err != nil {
		return fmt.Errorf("generating descriptor provider: %w", err)
	}

	// Generate per-scope Features classes if scopes are defined.
	scopes := contextutil.DiscoverScopes(plugin)
	if ctxDef != nil && len(scopes) > 0 {
		if err := generateScopeClasses(plugin, ctxDef, scopes, features, javaPackage, pkgDir); err != nil {
			return fmt.Errorf("generating scope classes: %w", err)
		}
	}

	return nil
}

func generateInterface(plugin *protogen.Plugin, feat *featureInfo, flags []flagInfo, javaPackage, pkgDir string) error {
	pascalFeat := toPascalCase(feat.id)
	className := pascalFeat + "Flags"
	outPath := pkgDir + "/" + className + ".java"

	g := plugin.NewGeneratedFile(outPath, "")
	p := g.P

	// Determine what imports we need.
	hasFlags := false
	hasListFlags := false
	for _, fl := range flags {
		if fl.isList {
			hasListFlags = true
		} else {
			hasFlags = true
		}
	}

	p("// Code generated by protoc-gen-pbflags. DO NOT EDIT.")
	p("package ", javaPackage, ";")
	p()
	if hasListFlags {
		p("import java.util.List;")
	}
	if hasFlags {
		p("import org.spotlightgov.pbflags.Flag;")
	}
	p("import org.spotlightgov.pbflags.FlagEvaluator;")
	if hasListFlags {
		p("import org.spotlightgov.pbflags.ListFlag;")
	}
	p()
	p("/**")
	p(" * Generated type-safe flag accessors for the {@code ", feat.id, "} feature.")
	if feat.description != "" {
		p(" *")
		p(" * <p>", feat.description)
	}
	p(" */")
	p("public interface ", className, " {")
	p()

	p("  String FEATURE_ID = ", quote(feat.id), ";")
	p()

	for _, fl := range flags {
		p("  String ", fl.constName, "_ID = ", quote(fmt.Sprintf("%s/%d", feat.id, fl.fieldNumber)), ";")
	}
	p()

	for _, fl := range flags {
		if fl.hasDefault {
			p("  ", fl.javaType, " ", fl.constName, "_DEFAULT = ", fl.defaultVal, ";")
		}
	}
	p()

	for _, fl := range flags {
		if fl.description != "" {
			p("  /** ", fl.description, " */")
		}
		if fl.isList {
			p("  ListFlag<", fl.javaBoxedType, "> ", fl.camelName, "();")
		} else {
			p("  Flag<", fl.javaBoxedType, "> ", fl.camelName, "();")
		}
		p()
	}

	p("  /**")
	p("   * Creates an instance backed by a {@link FlagEvaluator}.")
	p("   */")
	p("  static ", className, " forEvaluator(FlagEvaluator evaluator) {")
	p("    return new ", className, "() {")
	p()
	for i, fl := range flags {
		p("      @Override")
		if fl.isList {
			p("      public ListFlag<", fl.javaBoxedType, "> ", fl.camelName, "() {")
			p("        return evaluator.listFlag(", fl.constName, "_ID, ", fl.javaClassLiteral, ", ", javaDefaultExpr(fl), ");")
		} else {
			p("      public Flag<", fl.javaBoxedType, "> ", fl.camelName, "() {")
			p("        return evaluator.flag(", fl.constName, "_ID, ", fl.javaClassLiteral, ", ", javaDefaultExpr(fl), ");")
		}
		p("      }")
		if i < len(flags)-1 {
			p()
		}
	}
	p("    };")
	p("  }")
	p("}")

	return nil
}

func generateImpl(plugin *protogen.Plugin, feat *featureInfo, flags []flagInfo, javaPackage, pkgDir string, dagger bool) error {
	pascalFeat := toPascalCase(feat.id)
	interfaceName := pascalFeat + "Flags"
	className := pascalFeat + "FlagsImpl"
	outPath := pkgDir + "/" + className + ".java"

	g := plugin.NewGeneratedFile(outPath, "")
	p := g.P

	// Determine what imports we need.
	hasFlags := false
	hasListFlags := false
	for _, fl := range flags {
		if fl.isList {
			hasListFlags = true
		} else {
			hasFlags = true
		}
	}

	p("// Code generated by protoc-gen-pbflags. DO NOT EDIT.")
	p("package ", javaPackage, ";")
	p()
	if hasFlags {
		p("import org.spotlightgov.pbflags.Flag;")
	}
	p("import org.spotlightgov.pbflags.FlagEvaluator;")
	if hasListFlags {
		p("import org.spotlightgov.pbflags.ListFlag;")
	}
	p("import org.slf4j.Logger;")
	p("import org.slf4j.LoggerFactory;")
	if dagger {
		p("import javax.inject.Inject;")
		p("import javax.inject.Singleton;")
	}
	p()
	p("/** Generated implementation of {@link ", interfaceName, "}. */")
	if dagger {
		p("@Singleton")
	}
	p("public final class ", className, " implements ", interfaceName, " {")
	p()
	p("  private static final Logger logger = LoggerFactory.getLogger(", className, ".class);")
	p()

	for _, fl := range flags {
		if fl.isList {
			p("  private final ListFlag<", fl.javaBoxedType, "> ", fl.camelName, ";")
		} else {
			p("  private final Flag<", fl.javaBoxedType, "> ", fl.camelName, ";")
		}
	}
	p()

	if dagger {
		p("  @Inject")
	}
	p("  public ", className, "(FlagEvaluator evaluator) {")
	for _, fl := range flags {
		defExpr := javaDefaultExpr(fl)
		if fl.isList {
			p("    this.", fl.camelName, " = safeListFlag(evaluator, ", fl.constName, "_ID, ", fl.javaClassLiteral, ", ", defExpr, ");")
		} else {
			p("    this.", fl.camelName, " = safeFlag(evaluator, ", fl.constName, "_ID, ", fl.javaClassLiteral, ", ", defExpr, ");")
		}
	}
	p("  }")
	p()

	for _, fl := range flags {
		p("  @Override")
		if fl.isList {
			p("  public ListFlag<", fl.javaBoxedType, "> ", fl.camelName, "() {")
		} else {
			p("  public Flag<", fl.javaBoxedType, "> ", fl.camelName, "() {")
		}
		p("    return ", fl.camelName, ";")
		p("  }")
		p()
	}

	// Helper methods that wrap evaluator calls with logging.
	if hasFlags {
		p("  private static <T> Flag<T> safeFlag(FlagEvaluator evaluator, String flagId,")
		p("      Class<T> type, T compiledDefault) {")
		p("    return () -> {")
		p("      try {")
		p("        T value = evaluator.evaluate(flagId, type, compiledDefault);")
		p("        if (logger.isDebugEnabled()) {")
		p("          logger.debug(\"flag evaluated: {} = {} ({})\", flagId, value, type.getSimpleName());")
		p("        }")
		p("        return value;")
		p("      } catch (Exception e) {")
		p("        logger.error(\"Flag evaluation failed for {}, returning default\", flagId, e);")
		p("        return compiledDefault;")
		p("      }")
		p("    };")
		p("  }")
		p()
	}
	if hasListFlags {
		p("  private static <E> ListFlag<E> safeListFlag(FlagEvaluator evaluator, String flagId,")
		p("      Class<E> elementType, java.util.List<E> compiledDefault) {")
		p("    return () -> {")
		p("      try {")
		p("        java.util.List<E> value = evaluator.evaluateList(flagId, elementType, compiledDefault);")
		p("        if (logger.isDebugEnabled()) {")
		p("          logger.debug(\"list flag evaluated: {} = {} (List<{}>)\", flagId, value, elementType.getSimpleName());")
		p("        }")
		p("        return value;")
		p("      } catch (Exception e) {")
		p("        logger.error(\"List flag evaluation failed for {}, returning default\", flagId, e);")
		p("        return compiledDefault;")
		p("      }")
		p("    };")
		p("  }")
		p()
	}

	p("}")

	return nil
}

func generateTestImpl(plugin *protogen.Plugin, feat *featureInfo, flags []flagInfo, javaPackage, pkgDir string) error {
	pascalFeat := toPascalCase(feat.id)
	interfaceName := pascalFeat + "Flags"
	className := "Test" + pascalFeat + "Flags"
	outPath := pkgDir + "/" + className + ".java"

	g := plugin.NewGeneratedFile(outPath, "")
	p := g.P

	hasFlags := false
	hasListFlags := false
	for _, fl := range flags {
		if fl.isList {
			hasListFlags = true
		} else {
			hasFlags = true
		}
	}

	p("// Code generated by protoc-gen-pbflags. DO NOT EDIT.")
	p("package ", javaPackage, ";")
	p()
	if hasListFlags {
		p("import java.util.List;")
	}
	if hasFlags {
		p("import org.spotlightgov.pbflags.Flag;")
	}
	if hasListFlags {
		p("import org.spotlightgov.pbflags.ListFlag;")
	}
	p()
	p("/**")
	p(" * Mutable test stub for {@link ", interfaceName, "}.")
	p(" *")
	p(" * <p>Each flag accessor delegates to its corresponding field, which is pre-populated with the")
	p(" * compiled default. Override individual flags via the fluent setters.")
	p(" */")
	p("public final class ", className, " implements ", interfaceName, " {")
	p()

	// Fields: one per flag, pre-populated with compiled defaults.
	for _, fl := range flags {
		if fl.isList {
			p("  private ListFlag<", fl.javaBoxedType, "> ", fl.camelName, "Fn = () -> ", javaDefaultExpr(fl), ";")
		} else {
			p("  private Flag<", fl.javaBoxedType, "> ", fl.camelName, "Fn = () -> ", javaDefaultExpr(fl), ";")
		}
	}
	p()

	// Fluent value setters.
	for _, fl := range flags {
		if fl.isList {
			p("  /** Override {@code ", fl.camelName, "()} to return the given value. */")
			p("  public ", className, " ", fl.camelName, "(List<", fl.javaBoxedType, "> value) {")
			p("    this.", fl.camelName, "Fn = () -> value;")
			p("    return this;")
			p("  }")
			p()
		} else {
			p("  /** Override {@code ", fl.camelName, "()} to return the given value. */")
			p("  public ", className, " ", fl.camelName, "(", fl.javaType, " value) {")
			p("    this.", fl.camelName, "Fn = () -> value;")
			p("    return this;")
			p("  }")
			p()
		}
	}

	// Accessor methods delegating to the Fn fields.
	for _, fl := range flags {
		p("  @Override")
		if fl.isList {
			p("  public ListFlag<", fl.javaBoxedType, "> ", fl.camelName, "() {")
		} else {
			p("  public Flag<", fl.javaBoxedType, "> ", fl.camelName, "() {")
		}
		p("    return ", fl.camelName, "Fn;")
		p("  }")
		p()
	}

	p("}")

	return nil
}

func generateDaggerModule(plugin *protogen.Plugin, features []featureEntry, javaPackage, pkgDir string) error {
	outPath := pkgDir + "/FlagRegistryModule.java"
	g := plugin.NewGeneratedFile(outPath, "")
	p := g.P

	p("// Code generated by protoc-gen-pbflags. DO NOT EDIT.")
	p("package ", javaPackage, ";")
	p()
	p("import dagger.Binds;")
	p("import dagger.Module;")
	p()
	p("/** Generated Dagger module binding feature flag interfaces to their implementations. */")
	p("@Module")
	p("public interface FlagRegistryModule {")

	for _, entry := range features {
		pascalFeat := toPascalCase(entry.feat.id)
		interfaceName := pascalFeat + "Flags"
		implName := pascalFeat + "FlagsImpl"
		p()
		p("  @Binds")
		p("  ", interfaceName, " bind", pascalFeat, "Flags(", implName, " impl);")
	}

	p("}")

	return nil
}

func generateScopedEvaluatorModule(plugin *protogen.Plugin, javaPackage, pkgDir string) error {
	outPath := pkgDir + "/ScopedEvaluatorModule.java"
	g := plugin.NewGeneratedFile(outPath, "")
	p := g.P

	p("// Code generated by protoc-gen-pbflags. DO NOT EDIT.")
	p("package ", javaPackage, ";")
	p()
	p("import dagger.Module;")
	p("import dagger.Provides;")
	p("import org.spotlightgov.pbflags.FlagEvaluator;")
	p("import org.spotlightgov.pbflags.ScopedEvaluator;")
	p()
	p("/**")
	p(" * Dagger module providing the request-scoped {@link FlagEvaluator}.")
	p(" *")
	p(" * <p>Bind dimensions in request middleware via {@link ScopedEvaluator#bind}, then inject")
	p(" * {@link FlagEvaluator} into request-scoped components.")
	p(" */")
	p("@Module")
	p("public final class ScopedEvaluatorModule {")
	p()
	p("  @Provides")
	p("  static FlagEvaluator provideScopedEvaluator() {")
	p("    return ScopedEvaluator.current();")
	p("  }")
	p("}")

	return nil
}

func generateDescriptorProvider(plugin *protogen.Plugin, features []featureEntry, javaPackage, pkgDir string) error {
	// Collect unique proto source files.
	seen := map[string]bool{}
	var files []*protogen.File
	for _, entry := range features {
		path := entry.protoSrc.Desc.Path()
		if !seen[path] {
			seen[path] = true
			files = append(files, entry.protoSrc)
		}
	}

	outPath := pkgDir + "/PbflagsFlagDescriptorProvider.java"
	g := plugin.NewGeneratedFile(outPath, "")
	p := g.P

	p("// Code generated by protoc-gen-pbflags. DO NOT EDIT.")
	p("package ", javaPackage, ";")
	p()
	p("import com.google.protobuf.Descriptors.FileDescriptor;")
	p("import org.spotlightgov.pbflags.FlagDescriptorProvider;")
	p("import java.util.Arrays;")
	p("import java.util.List;")
	p()
	p("/** Generated {@link FlagDescriptorProvider} for feature flag proto descriptors. */")
	p("public final class PbflagsFlagDescriptorProvider implements FlagDescriptorProvider {")
	p()
	p("  @Override")
	p("  public List<FileDescriptor> fileDescriptors() {")
	p("    return Arrays.asList(")
	for i, f := range files {
		ref := protoOuterClassRef(f)
		comma := ","
		if i == len(files)-1 {
			comma = ""
		}
		p("        ", ref, ".getDescriptor()", comma)
	}
	p("    );")
	p("  }")
	p("}")

	return nil
}

// generateDimensionsClass generates a Dims.java class with typed dimension
// constructors from the EvaluationContext proto message.
func generateDimensionsClass(plugin *protogen.Plugin, ctx *contextutil.ContextDef, javaPackage string) error {
	pkgDir := strings.ReplaceAll(javaPackage, ".", "/")
	outPath := pkgDir + "/Dimensions.java"

	g := plugin.NewGeneratedFile(outPath, "")
	p := g.P

	p("// Code generated by protoc-gen-pbflags. DO NOT EDIT.")
	p("package ", javaPackage, ";")
	p()
	p("import org.spotlightgov.pbflags.Dimension;")
	p()
	p("/** Generated typed dimension constructors for the EvaluationContext. */")
	p("public final class Dimensions {")
	p()
	p("  private Dimensions() {}")

	for _, dim := range ctx.Dimensions {
		methodName := toCamelCase(dim.Name)
		desc := dim.Description
		if desc == "" {
			desc = dim.Name + " dimension"
		}

		p()
		switch dim.Kind {
		case contextutil.DimensionString:
			p("  /** Sets the ", dim.Name, " dimension (", desc, "). */")
			p("  public static Dimension ", methodName, "(String v) {")
			p("    return Dimension.ofString(", quote(dim.Name), ", v);")
			p("  }")

		case contextutil.DimensionBool:
			p("  /** Sets the ", dim.Name, " dimension (", desc, "). */")
			p("  public static Dimension ", methodName, "(boolean v) {")
			p("    return Dimension.ofBool(", quote(dim.Name), ", v);")
			p("  }")

		case contextutil.DimensionInt64:
			p("  /** Sets the ", dim.Name, " dimension (", desc, "). */")
			p("  public static Dimension ", methodName, "(long v) {")
			p("    return Dimension.ofInt64(", quote(dim.Name), ", v);")
			p("  }")

		case contextutil.DimensionEnum:
			// Derive the Java enum class reference from the proto enum.
			javaEnumRef := javaEnumReference(dim.ProtoField)
			p("  /** Sets the ", dim.Name, " dimension (", desc, "). */")
			p("  public static Dimension ", methodName, "(", javaEnumRef, " v) {")
			p("    return Dimension.ofEnum(", quote(dim.Name), ", v.getValueDescriptor());")
			p("  }")
		}
	}

	p("}")

	return nil
}

// generateScopeClasses generates per-scope Java classes (e.g., AnonFeatures, UserFeatures).
func generateScopeClasses(
	plugin *protogen.Plugin,
	ctxDef *contextutil.ContextDef,
	scopes []contextutil.ScopeDef,
	features []featureEntry,
	javaPackage, pkgDir string,
) error {
	dimByName := map[string]contextutil.DimensionDef{}
	for _, d := range ctxDef.Dimensions {
		dimByName[d.Name] = d
	}

	var globalDims []contextutil.DimensionDef
	for _, d := range ctxDef.Dimensions {
		if d.IsRequired() {
			globalDims = append(globalDims, d)
		}
	}

	featureScopeSet := map[string]map[string]bool{}
	for _, e := range features {
		featureScopeSet[e.feat.id] = map[string]bool{}
		for _, s := range e.feat.scopes {
			featureScopeSet[e.feat.id][s] = true
		}
	}

	for _, scope := range scopes {
		scopePascal := toPascalCase(scope.Name)
		className := scopePascal + "Features"

		var scopeDims []contextutil.DimensionDef
		scopeDims = append(scopeDims, globalDims...)
		for _, dimName := range scope.Dimensions {
			if d, ok := dimByName[dimName]; ok {
				scopeDims = append(scopeDims, d)
			}
		}

		var scopeFeatures []featureEntry
		for _, e := range features {
			if featureScopeSet[e.feat.id][scope.Name] {
				scopeFeatures = append(scopeFeatures, e)
			}
		}
		if len(scopeFeatures) == 0 {
			continue
		}

		outPath := pkgDir + "/" + className + ".java"
		g := plugin.NewGeneratedFile(outPath, "")
		p := g.P

		p("// Code generated by protoc-gen-pbflags. DO NOT EDIT.")
		p("package ", javaPackage, ";")
		p()
		p("import org.spotlightgov.pbflags.Dimension;")
		p("import org.spotlightgov.pbflags.FlagEvaluator;")
		p()
		p("/**")
		p(" * Feature flag accessor for the {@code ", scope.Name, "} evaluation scope.")
		p(" *")
		p(" * <p>Constructor requires all dimensions available in this scope.")
		p(" * Feature accessors are cached on first access.")
		p(" */")
		p("public final class ", className, " {")
		p()
		p("  private final FlagEvaluator eval;")
		for _, d := range scopeDims {
			jType := javaDimType(d)
			p("  private final ", jType, " ", toCamelCase(d.Name), ";")
		}
		for _, e := range scopeFeatures {
			ifaceName := toPascalCase(e.feat.id) + "Flags"
			p("  private ", ifaceName, " cached", toPascalCase(e.feat.id), ";")
		}
		p()

		// Constructor.
		var ctorParams []string
		ctorParams = append(ctorParams, "FlagEvaluator eval")
		for _, d := range scopeDims {
			ctorParams = append(ctorParams, javaDimType(d)+" "+toCamelCase(d.Name))
		}
		p("  public ", className, "(", strings.Join(ctorParams, ", "), ") {")
		p("    this.eval = eval;")
		for _, d := range scopeDims {
			camel := toCamelCase(d.Name)
			p("    this.", camel, " = ", camel, ";")
		}
		p("  }")
		p()

		// Feature accessors.
		for _, e := range scopeFeatures {
			pascal := toPascalCase(e.feat.id)
			ifaceName := pascal + "Flags"
			cachedField := "cached" + pascal

			p("  /** Returns a {@link ", ifaceName, "} client scoped to this evaluation context. */")
			p("  public ", ifaceName, " ", toCamelCase(e.feat.id), "() {")
			p("    if (this.", cachedField, " == null) {")
			p("      FlagEvaluator scoped = this.eval;")
			for _, d := range scopeDims {
				dimMethod := toCamelCase(d.Name)
				p("      scoped = scoped.with(Dimensions.", dimMethod, "(this.", dimMethod, "));")
			}
			p("      this.", cachedField, " = new ", pascal, "FlagsImpl(scoped);")
			p("    }")
			p("    return this.", cachedField, ";")
			p("  }")
			p()
		}

		p("}")
	}

	return nil
}

// javaDimType returns the Java type for a dimension kind.
func javaDimType(d contextutil.DimensionDef) string {
	switch d.Kind {
	case contextutil.DimensionBool:
		return "boolean"
	case contextutil.DimensionInt64:
		return "long"
	case contextutil.DimensionEnum:
		if d.ProtoField != nil {
			return javaEnumReference(d.ProtoField)
		}
		return "int"
	default:
		return "String"
	}
}

// javaEnumReference returns the fully qualified Java class name for a proto enum field.
// Reads java_package, java_multiple_files, and java_outer_classname from file options
// via protoreflect to derive the correct Java reference.
func javaEnumReference(field *protogen.Field) string {
	enumDesc := field.Desc.Enum()
	fileDesc := enumDesc.ParentFile()
	enumName := string(enumDesc.Name())

	// Read Java file options via protoreflect.
	var javaPkg string
	var javaMultipleFiles bool
	var javaOuterClassname string

	rm := fileDesc.Options().ProtoReflect()
	rm.Range(func(fd protoreflect.FieldDescriptor, v protoreflect.Value) bool {
		switch fd.Name() {
		case "java_package":
			javaPkg = v.String()
		case "java_multiple_files":
			javaMultipleFiles = v.Bool()
		case "java_outer_classname":
			javaOuterClassname = v.String()
		}
		return true
	})

	if javaPkg == "" {
		javaPkg = string(fileDesc.Package())
	}

	if javaMultipleFiles {
		return javaPkg + "." + enumName
	}

	if javaOuterClassname == "" {
		base := filepath.Base(string(fileDesc.Path()))
		base = strings.TrimSuffix(base, filepath.Ext(base))
		javaOuterClassname = toUnderscoreCamelCase(base)
	}

	return javaPkg + "." + javaOuterClassname + "." + enumName
}

// checkOuterClassCaseCollisions detects case-insensitive collisions between
// derived Java outer class names and top-level declarations. On case-insensitive
// filesystems (macOS APFS default), these produce silent file overwrites that
// result in uncompilable Java code. protoc only checks exact (case-sensitive)
// matches, so this fills the gap.
func checkOuterClassCaseCollisions(files []*protogen.File) error {
	for _, f := range files {
		// Explicit java_outer_classname means the user has already handled it.
		if f.Proto.GetOptions().GetJavaOuterClassname() != "" {
			continue
		}

		base := filepath.Base(f.Proto.GetName())
		base = strings.TrimSuffix(base, filepath.Ext(base))
		outerClass := toUnderscoreCamelCase(base)

		var declNames []string
		for _, msg := range f.Messages {
			declNames = append(declNames, string(msg.Desc.Name()))
		}
		for _, e := range f.Enums {
			declNames = append(declNames, string(e.Desc.Name()))
		}
		for _, s := range f.Services {
			declNames = append(declNames, string(s.Desc.Name()))
		}

		if collider := outerClassCaseCollision(outerClass, declNames); collider != "" {
			return fmt.Errorf(
				"protoc-gen-pbflags: %s: derived Java outer class %q case-insensitively collides "+
					"with %q — on case-insensitive filesystems (macOS APFS) this causes file overwrites "+
					"and uncompilable Java code. Fix: add 'option java_outer_classname = \"...\";' to %s",
				f.Proto.GetName(), outerClass, collider, f.Proto.GetName())
		}
	}
	return nil
}

// outerClassCaseCollision checks whether outerClass case-insensitively matches
// any name in declNames that is NOT an exact match (exact matches are already
// handled by protoFileToOuterClass appending "OuterClass"). Returns the
// colliding name or "".
func outerClassCaseCollision(outerClass string, declNames []string) string {
	for _, name := range declNames {
		if name != outerClass && strings.EqualFold(name, outerClass) {
			return name
		}
	}
	return ""
}

// protoOuterClassRef returns the fully qualified Java outer class reference for a proto file.
// This is the class that holds the static getDescriptor() method for the file.
func protoOuterClassRef(f *protogen.File) string {
	javaPkg := f.Proto.GetOptions().GetJavaPackage()
	if javaPkg == "" {
		javaPkg = string(f.Proto.GetPackage())
	}

	outerClass := f.Proto.GetOptions().GetJavaOuterClassname()
	if outerClass == "" {
		outerClass = protoFileToOuterClass(f)
	}

	return javaPkg + "." + outerClass
}

// protoFileToOuterClass derives the Java outer class name from a proto file,
// following protoc's algorithm: CamelCase the filename, append "OuterClass" if
// it conflicts with a top-level message, enum, or service name.
func protoFileToOuterClass(f *protogen.File) string {
	base := filepath.Base(f.Proto.GetName())
	base = strings.TrimSuffix(base, filepath.Ext(base))
	name := toUnderscoreCamelCase(base)

	// Check for conflicts with top-level declarations.
	for _, msg := range f.Messages {
		if string(msg.Desc.Name()) == name {
			return name + "OuterClass"
		}
	}
	for _, e := range f.Enums {
		if string(e.Desc.Name()) == name {
			return name + "OuterClass"
		}
	}
	for _, s := range f.Services {
		if string(s.Desc.Name()) == name {
			return name + "OuterClass"
		}
	}

	return name
}

// toUnderscoreCamelCase converts a proto filename base (e.g. "my_file") to CamelCase ("MyFile"),
// matching protoc's java_outer_classname derivation.
func toUnderscoreCamelCase(s string) string {
	var result strings.Builder
	upper := true
	for _, c := range s {
		if c == '_' || c == '-' {
			upper = true
			continue
		}
		if upper {
			result.WriteRune(rune(strings.ToUpper(string(c))[0]))
			upper = false
		} else {
			result.WriteRune(c)
		}
	}
	return result.String()
}

// --- Types ---

type featureInfo struct {
	id          string
	description string
	owner       string
	scopes      []string
}

type flagInfo struct {
	camelName        string
	constName        string
	fieldNumber      int32
	javaType         string
	javaBoxedType    string
	javaClassLiteral string
	defaultVal       string
	hasDefault       bool
	isList           bool // true for repeated (list-valued) flags
	description      string
}

func javaDefaultExpr(fl flagInfo) string {
	if fl.hasDefault {
		return fl.constName + "_DEFAULT"
	}
	if fl.isList {
		return "java.util.List.of()"
	}
	switch fl.javaType {
	case "boolean":
		return "false"
	case "String":
		return `""`
	case "long":
		return "0L"
	case "double":
		return "0.0"
	default:
		return "null"
	}
}

// --- Extraction (mirrors gogen) ---

func extractFeatureOptions(msg *protogen.Message) *featureInfo {
	opts := msg.Desc.Options()
	if opts == nil {
		return nil
	}
	protoMsg := opts.(interface{ ProtoReflect() protoreflect.Message })
	rm := protoMsg.ProtoReflect()

	var feat *featureInfo
	rm.Range(func(fd protoreflect.FieldDescriptor, v protoreflect.Value) bool {
		if fd.Number() == 51000 && fd.IsExtension() {
			m := v.Message()
			info := &featureInfo{}
			m.Range(func(innerFd protoreflect.FieldDescriptor, innerV protoreflect.Value) bool {
				switch innerFd.Name() {
				case "id":
					info.id = innerV.String()
				case "description":
					info.description = innerV.String()
				case "owner":
					info.owner = innerV.String()
				case "scopes":
					list := innerV.List()
					for i := 0; i < list.Len(); i++ {
						info.scopes = append(info.scopes, list.Get(i).String())
					}
				}
				return true
			})
			if info.id != "" {
				feat = info
			}
			return false
		}
		return true
	})
	if feat != nil {
		return feat
	}

	unk := rm.GetUnknown()
	if len(unk) == 0 {
		return nil
	}
	return parseFeatureFromUnknown(unk)
}

func parseFeatureFromUnknown(b []byte) *featureInfo {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return nil
		}
		b = b[n:]
		if num == 51000 && typ == protowire.BytesType {
			data, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return nil
			}
			return parseFeatureMessage(data)
		}
		n = skipField(b, typ)
		if n < 0 {
			return nil
		}
		b = b[n:]
	}
	return nil
}

func parseFeatureMessage(b []byte) *featureInfo {
	info := &featureInfo{}
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return nil
		}
		b = b[n:]
		if typ != protowire.BytesType {
			n = skipField(b, typ)
			if n < 0 {
				return nil
			}
			b = b[n:]
			continue
		}
		data, n := protowire.ConsumeBytes(b)
		if n < 0 {
			return nil
		}
		b = b[n:]
		switch num {
		case 1:
			info.id = string(data)
		case 2:
			info.description = string(data)
		case 3:
			info.owner = string(data)
		case 4: // repeated string scopes
			info.scopes = append(info.scopes, string(data))
		}
	}
	if info.id == "" {
		return nil
	}
	return info
}

func extractFlags(msg *protogen.Message) ([]flagInfo, error) {
	var flags []flagInfo
	for _, field := range msg.Fields {
		fl, err := extractFlagFromField(field)
		if err != nil {
			return nil, err
		}
		if fl != nil {
			flags = append(flags, *fl)
		}
	}
	return flags, nil
}

func extractFlagFromField(field *protogen.Field) (*flagInfo, error) {
	opts := field.Desc.Options()
	if opts == nil {
		return nil, nil
	}
	protoMsg := opts.(interface{ ProtoReflect() protoreflect.Message })
	rm := protoMsg.ProtoReflect()

	var found bool
	var defaultVal string
	var hasDefault bool
	var description string

	rm.Range(func(fd protoreflect.FieldDescriptor, v protoreflect.Value) bool {
		if fd.Number() == 51001 && fd.IsExtension() {
			found = true
			m := v.Message()
			m.Range(func(innerFd protoreflect.FieldDescriptor, innerV protoreflect.Value) bool {
				switch innerFd.Name() {
				case "default":
					defaultVal, hasDefault = extractDefaultReflect(innerV.Message(), field.Desc.Kind())
				case "description":
					description = innerV.String()
				}
				return true
			})
			return false
		}
		return true
	})

	if !found {
		unk := rm.GetUnknown()
		if len(unk) == 0 {
			return nil, nil
		}
		found, defaultVal, hasDefault, description = parseFlagFromUnknown(unk, field.Desc.Kind())
		if !found {
			return nil, nil
		}
	}

	fieldName := string(field.Desc.Name())
	isList := field.Desc.IsList()
	javaType, javaBoxedType, javaClassLiteral := javaTypeInfo(field.Desc.Kind(), isList)

	return &flagInfo{
		camelName:        toCamelCase(fieldName),
		constName:        toScreamingSnake(fieldName),
		fieldNumber:      int32(field.Desc.Number()),
		javaType:         javaType,
		javaBoxedType:    javaBoxedType,
		javaClassLiteral: javaClassLiteral,
		defaultVal:       defaultVal,
		hasDefault:       hasDefault,
		isList:           isList,
		description:      description,
	}, nil
}

func extractDefaultReflect(defMsg protoreflect.Message, fieldKind protoreflect.Kind) (string, bool) {
	var val string
	var ok bool
	defMsg.Range(func(fd protoreflect.FieldDescriptor, v protoreflect.Value) bool {
		switch fd.Name() {
		case "bool_list_value", "string_list_value", "int64_list_value", "double_list_value":
			val, ok = extractListDefaultReflect(fd.Name(), v.Message())
			return false
		}
		wrapperMsg := v.Message()
		wrapperMsg.Range(func(wfd protoreflect.FieldDescriptor, wv protoreflect.Value) bool {
			if wfd.Name() != "value" {
				return true
			}
			switch fd.Name() {
			case "bool_value":
				ok = true
				if wv.Bool() {
					val = "true"
				} else {
					val = "false"
				}
			case "string_value":
				ok = true
				val = fmt.Sprintf("%q", wv.String())
			case "int64_value":
				ok = true
				val = fmt.Sprintf("%dL", wv.Int())
			case "double_value":
				ok = true
				val = formatJavaDouble(wv.Float())
			}
			return false
		})
		return false
	})
	return val, ok
}

func extractListDefaultReflect(fieldName protoreflect.Name, listMsg protoreflect.Message) (string, bool) {
	valField := listMsg.Descriptor().Fields().ByNumber(1)
	if valField == nil {
		return "", false
	}
	list := listMsg.Get(valField).List()
	var items []string
	for i := 0; i < list.Len(); i++ {
		switch fieldName {
		case "bool_list_value":
			if list.Get(i).Bool() {
				items = append(items, "true")
			} else {
				items = append(items, "false")
			}
		case "string_list_value":
			items = append(items, fmt.Sprintf("%q", list.Get(i).String()))
		case "int64_list_value":
			items = append(items, fmt.Sprintf("%dL", list.Get(i).Int()))
		case "double_list_value":
			items = append(items, formatJavaDouble(list.Get(i).Float()))
		}
	}
	return "java.util.List.of(" + strings.Join(items, ", ") + ")", true
}

func parseFlagFromUnknown(b []byte, fieldKind protoreflect.Kind) (found bool, defaultVal string, hasDefault bool, description string) {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return
		}
		b = b[n:]
		if num == 51001 && typ == protowire.BytesType {
			data, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return
			}
			found = true
			defaultVal, hasDefault, description = parseFlagOptionsMessage(data, fieldKind)
			return
		}
		n = skipField(b, typ)
		if n < 0 {
			return
		}
		b = b[n:]
	}
	return
}

func parseFlagOptionsMessage(b []byte, fieldKind protoreflect.Kind) (defaultVal string, hasDefault bool, description string) {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return
		}
		b = b[n:]
		switch num {
		case 1:
			if typ == protowire.BytesType {
				data, n := protowire.ConsumeBytes(b)
				if n < 0 {
					return
				}
				b = b[n:]
				description = string(data)
				continue
			}
		case 2:
			if typ == protowire.BytesType {
				data, n := protowire.ConsumeBytes(b)
				if n < 0 {
					return
				}
				b = b[n:]
				defaultVal, hasDefault = parseFlagDefault(data, fieldKind)
				continue
			}
		}
		n = skipField(b, typ)
		if n < 0 {
			return
		}
		b = b[n:]
	}
	return
}

func parseFlagDefault(b []byte, fieldKind protoreflect.Kind) (string, bool) {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return "", false
		}
		b = b[n:]
		if typ == protowire.BytesType {
			data, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return "", false
			}
			b = b[n:]
			switch num {
			case 1:
				return parseBoolWrapper(data)
			case 2:
				return parseStringWrapper(data)
			case 3:
				return parseInt64Wrapper(data)
			case 4:
				return parseDoubleWrapper(data)
			case 5:
				return parseBoolListMessage(data)
			case 6:
				return parseStringListMessage(data)
			case 7:
				return parseInt64ListMessage(data)
			case 8:
				return parseDoubleListMessage(data)
			}
			continue
		}
		n = skipField(b, typ)
		if n < 0 {
			return "", false
		}
		b = b[n:]
	}
	return "", false
}

func parseBoolListMessage(b []byte) (string, bool) {
	var items []string
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			break
		}
		b = b[n:]
		if num == 1 && typ == protowire.VarintType {
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				break
			}
			b = b[n:]
			if v != 0 {
				items = append(items, "true")
			} else {
				items = append(items, "false")
			}
			continue
		}
		n = skipField(b, typ)
		if n < 0 {
			break
		}
		b = b[n:]
	}
	return "java.util.List.of(" + strings.Join(items, ", ") + ")", true
}

func parseStringListMessage(b []byte) (string, bool) {
	var items []string
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			break
		}
		b = b[n:]
		if num == 1 && typ == protowire.BytesType {
			data, n := protowire.ConsumeBytes(b)
			if n < 0 {
				break
			}
			b = b[n:]
			items = append(items, fmt.Sprintf("%q", string(data)))
			continue
		}
		n = skipField(b, typ)
		if n < 0 {
			break
		}
		b = b[n:]
	}
	return "java.util.List.of(" + strings.Join(items, ", ") + ")", true
}

func parseInt64ListMessage(b []byte) (string, bool) {
	var items []string
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			break
		}
		b = b[n:]
		if num == 1 && typ == protowire.VarintType {
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				break
			}
			b = b[n:]
			items = append(items, fmt.Sprintf("%dL", int64(v)))
			continue
		}
		n = skipField(b, typ)
		if n < 0 {
			break
		}
		b = b[n:]
	}
	return "java.util.List.of(" + strings.Join(items, ", ") + ")", true
}

func parseDoubleListMessage(b []byte) (string, bool) {
	var items []string
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			break
		}
		b = b[n:]
		if num == 1 && typ == protowire.Fixed64Type {
			v, n := protowire.ConsumeFixed64(b)
			if n < 0 {
				break
			}
			b = b[n:]
			items = append(items, formatJavaDouble(math.Float64frombits(v)))
			continue
		}
		n = skipField(b, typ)
		if n < 0 {
			break
		}
		b = b[n:]
	}
	return "java.util.List.of(" + strings.Join(items, ", ") + ")", true
}

func parseBoolWrapper(b []byte) (string, bool) {
	val := false
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return "", false
		}
		b = b[n:]
		if num == 1 && typ == protowire.VarintType {
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				return "", false
			}
			b = b[n:]
			val = v != 0
			continue
		}
		n = skipField(b, typ)
		if n < 0 {
			return "", false
		}
		b = b[n:]
	}
	if val {
		return "true", true
	}
	return "false", true
}

func parseStringWrapper(b []byte) (string, bool) {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return "", false
		}
		b = b[n:]
		if num == 1 && typ == protowire.BytesType {
			data, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return "", false
			}
			return fmt.Sprintf("%q", string(data)), true
		}
		n = skipField(b, typ)
		if n < 0 {
			return "", false
		}
		b = b[n:]
	}
	return `""`, true
}

func parseInt64Wrapper(b []byte) (string, bool) {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return "", false
		}
		b = b[n:]
		if num == 1 && typ == protowire.VarintType {
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				return "", false
			}
			return fmt.Sprintf("%dL", int64(v)), true
		}
		n = skipField(b, typ)
		if n < 0 {
			return "", false
		}
		b = b[n:]
	}
	return "0L", true
}

func parseDoubleWrapper(b []byte) (string, bool) {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return "", false
		}
		b = b[n:]
		if num == 1 && typ == protowire.Fixed64Type {
			v, n := protowire.ConsumeFixed64(b)
			if n < 0 {
				return "", false
			}
			return formatJavaDouble(math.Float64frombits(v)), true
		}
		n = skipField(b, typ)
		if n < 0 {
			return "", false
		}
		b = b[n:]
	}
	return "0.0", true
}

func skipField(b []byte, typ protowire.Type) int {
	switch typ {
	case protowire.VarintType:
		_, n := protowire.ConsumeVarint(b)
		return n
	case protowire.Fixed32Type:
		_, n := protowire.ConsumeFixed32(b)
		return n
	case protowire.Fixed64Type:
		_, n := protowire.ConsumeFixed64(b)
		return n
	case protowire.BytesType:
		_, n := protowire.ConsumeBytes(b)
		return n
	default:
		return -1
	}
}

func javaTypeInfo(kind protoreflect.Kind, isList bool) (javaType, javaBoxedType, classLiteral string) {
	if isList {
		// For list types, javaBoxedType is the element type (used with ListFlag<E>).
		switch kind {
		case protoreflect.BoolKind:
			return "java.util.List<Boolean>", "Boolean", "Boolean.class"
		case protoreflect.StringKind:
			return "java.util.List<String>", "String", "String.class"
		case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
			return "java.util.List<Long>", "Long", "Long.class"
		case protoreflect.DoubleKind:
			return "java.util.List<Double>", "Double", "Double.class"
		default:
			return "java.util.List<Object>", "Object", "Object.class"
		}
	}
	switch kind {
	case protoreflect.BoolKind:
		return "boolean", "Boolean", "Boolean.class"
	case protoreflect.StringKind:
		return "String", "String", "String.class"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return "long", "Long", "Long.class"
	case protoreflect.DoubleKind:
		return "double", "Double", "Double.class"
	default:
		return "Object", "Object", "Object.class"
	}
}

func formatJavaDouble(f float64) string {
	s := fmt.Sprintf("%v", f)
	if !strings.Contains(s, ".") {
		s += ".0"
	}
	return s
}

func toPascalCase(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

func toCamelCase(s string) string {
	pascal := toPascalCase(s)
	if len(pascal) == 0 {
		return pascal
	}
	return strings.ToLower(pascal[:1]) + pascal[1:]
}

func toScreamingSnake(s string) string {
	return strings.ToUpper(s)
}

func quote(s string) string {
	return fmt.Sprintf("%q", s)
}
