// Code generated by protoc-gen-pbflags. DO NOT EDIT.
package org.spotlightgov.pbflags.generated;

import org.spotlightgov.pbflags.Dimension;
import org.spotlightgov.pbflags.FlagEvaluator;

/**
 * Feature flag accessor for the {@code anon} evaluation scope.
 *
 * <p>Constructor requires all dimensions available in this scope.
 * Feature accessors are cached on first access.
 */
public final class AnonFeatures {

  private final FlagEvaluator eval;
  private final String sessionId;
  private NotificationsFlags cachedNotifications;

  public AnonFeatures(FlagEvaluator eval, String sessionId) {
    this.eval = eval;
    this.sessionId = sessionId;
  }

  /** Returns a {@link NotificationsFlags} client scoped to this evaluation context. */
  public NotificationsFlags notifications() {
    if (this.cachedNotifications == null) {
      FlagEvaluator scoped = this.eval;
      scoped = scoped.with(Dimensions.sessionId(this.sessionId));
      this.cachedNotifications = new NotificationsFlagsImpl(scoped);
    }
    return this.cachedNotifications;
  }

}
