// Code generated by protoc-gen-pbflags. DO NOT EDIT.
package org.spotlightgov.pbflags.generated;

import org.spotlightgov.pbflags.Flag;
import org.spotlightgov.pbflags.FlagEvaluator;
import org.spotlightgov.pbflags.LayerFlag;
import org.spotlightgov.pbflags.generated.layers.UserID;

/** Generated implementation of {@link NotificationsFlags}. */
public final class NotificationsFlagsImpl implements NotificationsFlags {

  private final LayerFlag<Boolean, UserID> emailEnabled;
  private final Flag<String> digestFrequency;
  private final Flag<Long> maxRetries;
  private final Flag<Double> scoreThreshold;

  public NotificationsFlagsImpl(FlagEvaluator evaluator) {
    this.emailEnabled =
        evaluator.layerFlag(EMAIL_ENABLED_ID, Boolean.class, EMAIL_ENABLED_DEFAULT, UserID::value);
    this.digestFrequency =
        evaluator.flag(DIGEST_FREQUENCY_ID, String.class, DIGEST_FREQUENCY_DEFAULT);
    this.maxRetries =
        evaluator.flag(MAX_RETRIES_ID, Long.class, MAX_RETRIES_DEFAULT);
    this.scoreThreshold =
        evaluator.flag(SCORE_THRESHOLD_ID, Double.class, SCORE_THRESHOLD_DEFAULT);
  }

  @Override
  public LayerFlag<Boolean, UserID> emailEnabled() {
    return emailEnabled;
  }

  @Override
  public Flag<String> digestFrequency() {
    return digestFrequency;
  }

  @Override
  public Flag<Long> maxRetries() {
    return maxRetries;
  }

  @Override
  public Flag<Double> scoreThreshold() {
    return scoreThreshold;
  }

}
