// Code generated by protoc-gen-pbflags. DO NOT EDIT.
package org.spotlightgov.pbflags.generated;

import org.spotlightgov.pbflags.Flag;
import org.spotlightgov.pbflags.FlagEvaluator;
import org.spotlightgov.pbflags.ListFlag;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/** Generated implementation of {@link NotificationsFlags}. */
public final class NotificationsFlagsImpl implements NotificationsFlags {

  private static final Logger logger = LoggerFactory.getLogger(NotificationsFlagsImpl.class);

  private final Flag<Boolean> emailEnabled;
  private final Flag<String> digestFrequency;
  private final Flag<Long> maxRetries;
  private final Flag<Double> scoreThreshold;
  private final ListFlag<String> notificationEmails;
  private final ListFlag<Long> retryDelays;

  public NotificationsFlagsImpl(FlagEvaluator evaluator) {
    this.emailEnabled = safeFlag(evaluator, EMAIL_ENABLED_ID, Boolean.class, EMAIL_ENABLED_DEFAULT);
    this.digestFrequency = safeFlag(evaluator, DIGEST_FREQUENCY_ID, String.class, DIGEST_FREQUENCY_DEFAULT);
    this.maxRetries = safeFlag(evaluator, MAX_RETRIES_ID, Long.class, MAX_RETRIES_DEFAULT);
    this.scoreThreshold = safeFlag(evaluator, SCORE_THRESHOLD_ID, Double.class, SCORE_THRESHOLD_DEFAULT);
    this.notificationEmails = safeListFlag(evaluator, NOTIFICATION_EMAILS_ID, String.class, NOTIFICATION_EMAILS_DEFAULT);
    this.retryDelays = safeListFlag(evaluator, RETRY_DELAYS_ID, Long.class, RETRY_DELAYS_DEFAULT);
  }

  @Override
  public Flag<Boolean> emailEnabled() {
    return emailEnabled;
  }

  @Override
  public Flag<String> digestFrequency() {
    return digestFrequency;
  }

  @Override
  public Flag<Long> maxRetries() {
    return maxRetries;
  }

  @Override
  public Flag<Double> scoreThreshold() {
    return scoreThreshold;
  }

  @Override
  public ListFlag<String> notificationEmails() {
    return notificationEmails;
  }

  @Override
  public ListFlag<Long> retryDelays() {
    return retryDelays;
  }

  private static <T> Flag<T> safeFlag(FlagEvaluator evaluator, String flagId,
      Class<T> type, T compiledDefault) {
    return () -> {
      try {
        return evaluator.evaluate(flagId, type, compiledDefault);
      } catch (Exception e) {
        logger.error("Flag evaluation failed for {}, returning default", flagId, e);
        return compiledDefault;
      }
    };
  }

  private static <E> ListFlag<E> safeListFlag(FlagEvaluator evaluator, String flagId,
      Class<E> elementType, java.util.List<E> compiledDefault) {
    return () -> {
      try {
        return evaluator.evaluateList(flagId, elementType, compiledDefault);
      } catch (Exception e) {
        logger.error("List flag evaluation failed for {}, returning default", flagId, e);
        return compiledDefault;
      }
    };
  }

}
