FROM alpine:3.23

ARG TARGETARCH
RUN apk add --no-cache ca-certificates
COPY linux/${TARGETARCH}/pbflags-admin /usr/local/bin/pbflags-admin
COPY linux/${TARGETARCH}/pbflags-evaluator /usr/local/bin/pbflags-evaluator
COPY linux/${TARGETARCH}/pbflags /usr/local/bin/pbflags

EXPOSE 9200 9201

ENTRYPOINT ["pbflags-admin"]
