// Code generated by protoc-gen-pbflags. DO NOT EDIT.

package flagmeta

import "log/slog"

// Option configures a generated flag client.
type Option func(*Config)

// Config holds settings for a generated flag client.
type Config struct {
	Logger *slog.Logger
}

// WithLogger sets a custom logger for flag evaluation errors.
// By default, clients log via slog.Default().
func WithLogger(l *slog.Logger) Option {
	return func(c *Config) { c.Logger = l }
}

// Apply builds a Config from the given options, using slog.Default() when
// no logger is provided.
func Apply(opts ...Option) Config {
	cfg := Config{Logger: slog.Default()}
	for _, o := range opts {
		o(&cfg)
	}
	return cfg
}

// FlagType identifies the underlying scalar type of a flag.
type FlagType int

const (
	FlagTypeBool FlagType = iota
	FlagTypeString
	FlagTypeInt64
	FlagTypeDouble
)

// String returns the Go type name for the flag type.
func (t FlagType) String() string {
	switch t {
	case FlagTypeBool:
		return "bool"
	case FlagTypeString:
		return "string"
	case FlagTypeInt64:
		return "int64"
	case FlagTypeDouble:
		return "float64"
	default:
		return "unknown"
	}
}

// FlagDescriptor provides structured metadata about a single flag.
type FlagDescriptor struct {
	ID        string   // Flag ID (e.g., "notifications/1").
	FieldName string   // Proto field name (e.g., "email_enabled").
	Type      FlagType // Underlying scalar type.
	IsList    bool     // True for repeated (list-valued) flags.

	// Compiled default value. Only the field matching Type (and IsList) is populated.
	DefaultBool    bool
	DefaultString  string
	DefaultInt64   int64
	DefaultDouble  float64
	DefaultBools   []bool
	DefaultStrings []string
	DefaultInt64s  []int64
	DefaultDoubles []float64
}
