// Code generated by protoc-gen-pbflags. DO NOT EDIT.

package notificationsflags

import (
	"context"

	"connectrpc.com/connect"
	pbflagsv1 "github.com/SpotlightGOV/pbflags/gen/flags/v1"
	"github.com/SpotlightGOV/pbflags/gen/flags/v1/pbflagsv1connect"
	"github.com/SpotlightGOV/pbflags/gen/flags/layers"
)

const FeatureID = "notifications"

// Flag ID constants. Format: feature_id/field_number.
const (
	EmailEnabledID    = "notifications/1"
	DigestFrequencyID = "notifications/2"
	MaxRetriesID      = "notifications/3"
	ScoreThresholdID  = "notifications/4"
)

// Compiled defaults from proto annotations.
const (
	EmailEnabledDefault    = true
	DigestFrequencyDefault = "daily"
	MaxRetriesDefault      = int64(3)
	ScoreThresholdDefault  = float64(0.75)
)

// NotificationsFlags provides type-safe access to notifications feature flags.
type NotificationsFlags interface {
	EmailEnabled(ctx context.Context, user layers.UserID) bool
	DigestFrequency(ctx context.Context) string
	MaxRetries(ctx context.Context) int64
	ScoreThreshold(ctx context.Context) float64

	// Status returns the evaluator's current health state.
	Status(ctx context.Context) pbflagsv1.EvaluatorStatus
}

// NewNotificationsFlagsClient creates a client backed by a FlagEvaluator connection.
func NewNotificationsFlagsClient(evaluator pbflagsv1connect.FlagEvaluatorServiceClient) NotificationsFlags {
	return &notificationsFlagsClient{evaluator: evaluator}
}

type notificationsFlagsClient struct {
	evaluator pbflagsv1connect.FlagEvaluatorServiceClient
}

func (c *notificationsFlagsClient) EmailEnabled(ctx context.Context, user layers.UserID) bool {
	resp, err := c.evaluator.Evaluate(ctx, connect.NewRequest(&pbflagsv1.EvaluateRequest{
		FlagId:   EmailEnabledID,
		EntityId: user.String(),
	}))
	if err != nil {
		return EmailEnabledDefault
	}
	if _, ok := resp.Msg.GetValue().GetValue().(*pbflagsv1.FlagValue_BoolValue); !ok {
		return EmailEnabledDefault
	}
	return resp.Msg.GetValue().GetBoolValue()
}

func (c *notificationsFlagsClient) DigestFrequency(ctx context.Context) string {
	resp, err := c.evaluator.Evaluate(ctx, connect.NewRequest(&pbflagsv1.EvaluateRequest{
		FlagId: DigestFrequencyID,
	}))
	if err != nil {
		return DigestFrequencyDefault
	}
	if _, ok := resp.Msg.GetValue().GetValue().(*pbflagsv1.FlagValue_StringValue); !ok {
		return DigestFrequencyDefault
	}
	return resp.Msg.GetValue().GetStringValue()
}

func (c *notificationsFlagsClient) MaxRetries(ctx context.Context) int64 {
	resp, err := c.evaluator.Evaluate(ctx, connect.NewRequest(&pbflagsv1.EvaluateRequest{
		FlagId: MaxRetriesID,
	}))
	if err != nil {
		return MaxRetriesDefault
	}
	if _, ok := resp.Msg.GetValue().GetValue().(*pbflagsv1.FlagValue_Int64Value); !ok {
		return MaxRetriesDefault
	}
	return resp.Msg.GetValue().GetInt64Value()
}

func (c *notificationsFlagsClient) ScoreThreshold(ctx context.Context) float64 {
	resp, err := c.evaluator.Evaluate(ctx, connect.NewRequest(&pbflagsv1.EvaluateRequest{
		FlagId: ScoreThresholdID,
	}))
	if err != nil {
		return ScoreThresholdDefault
	}
	if _, ok := resp.Msg.GetValue().GetValue().(*pbflagsv1.FlagValue_DoubleValue); !ok {
		return ScoreThresholdDefault
	}
	return resp.Msg.GetValue().GetDoubleValue()
}

func (c *notificationsFlagsClient) Status(ctx context.Context) pbflagsv1.EvaluatorStatus {
	resp, err := c.evaluator.Health(ctx, connect.NewRequest(&pbflagsv1.HealthRequest{}))
	if err != nil {
		return pbflagsv1.EvaluatorStatus_EVALUATOR_STATUS_UNSPECIFIED
	}
	return resp.Msg.Status
}

// Defaults returns a NotificationsFlags that always returns the compiled
// default for every flag. Use this when no evaluator is available to avoid
// nil checks at call sites.
func Defaults() NotificationsFlags {
	return defaultNotificationsFlags{}
}

type defaultNotificationsFlags struct{}

func (defaultNotificationsFlags) EmailEnabled(_ context.Context, _ layers.UserID) bool {
	return EmailEnabledDefault
}

func (defaultNotificationsFlags) DigestFrequency(_ context.Context) string {
	return DigestFrequencyDefault
}

func (defaultNotificationsFlags) MaxRetries(_ context.Context) int64 {
	return MaxRetriesDefault
}

func (defaultNotificationsFlags) ScoreThreshold(_ context.Context) float64 {
	return ScoreThresholdDefault
}

func (defaultNotificationsFlags) Status(_ context.Context) pbflagsv1.EvaluatorStatus {
	return pbflagsv1.EvaluatorStatus_EVALUATOR_STATUS_UNSPECIFIED
}
