// Package configexport generates YAML flag configuration files from existing
// database state. This is the migration bridge from DB-driven to config-driven
// flags: global values become static entries, per-entity overrides become
// ctx.<entityDim> conditions.
package configexport

import (
	"context"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5/pgxpool"
	"google.golang.org/protobuf/proto"
	"gopkg.in/yaml.v3"

	pbflagsv1 "github.com/SpotlightGOV/pbflags/gen/pbflags/v1"
	"github.com/SpotlightGOV/pbflags/internal/flagfmt"
)

// ExportedConfig is a single feature's generated YAML config.
type ExportedConfig struct {
	FeatureID string
	YAML      []byte
}

// Options configures the export.
type Options struct {
	// EntityDimension is the context dimension name used for per-entity
	// override conditions (e.g., "user_id", "account_id"). Required when
	// the database has overrides. The exporter does not assume a default.
	EntityDimension string
}

// Export reads all non-archived features and their flags from the database
// and generates one YAML config per feature.
func Export(ctx context.Context, pool *pgxpool.Pool, opts Options) ([]ExportedConfig, error) {
	features, err := loadFeatures(ctx, pool)
	if err != nil {
		return nil, err
	}

	var configs []ExportedConfig
	for _, f := range features {
		data, err := generateYAML(f, opts)
		if err != nil {
			return nil, fmt.Errorf("feature %q: %w", f.id, err)
		}
		configs = append(configs, ExportedConfig{FeatureID: f.id, YAML: data})
	}
	return configs, nil
}

type feature struct {
	id    string
	flags []flag
}

type flag struct {
	flagID   string
	name     string
	flagType string
	killed   bool
	value    *pbflagsv1.FlagValue
}

func loadFeatures(ctx context.Context, pool *pgxpool.Pool) ([]feature, error) {
	rows, err := pool.Query(ctx, `
		SELECT fl.flag_id, fl.feature_id, fl.display_name, fl.flag_type,
		       fl.killed_at, fl.default_value
		FROM feature_flags.flags fl
		WHERE fl.archived_at IS NULL
		ORDER BY fl.feature_id, fl.field_number`)
	if err != nil {
		return nil, fmt.Errorf("query flags: %w", err)
	}
	defer rows.Close()

	featureMap := map[string]*feature{}
	var featureOrder []string

	for rows.Next() {
		var flagID, featureID, flagName, flagType string
		var killedAt *string
		var defaultBytes []byte
		if err := rows.Scan(&flagID, &featureID, &flagName, &flagType, &killedAt, &defaultBytes); err != nil {
			return nil, fmt.Errorf("scan flag: %w", err)
		}

		f, ok := featureMap[featureID]
		if !ok {
			f = &feature{id: featureID}
			featureMap[featureID] = f
			featureOrder = append(featureOrder, featureID)
		}

		val, err := unmarshalValue(defaultBytes)
		if err != nil {
			return nil, fmt.Errorf("unmarshal default_value for %s: %w", flagID, err)
		}

		fl := flag{
			flagID:   flagID,
			name:     flagName,
			flagType: flagType,
			killed:   killedAt != nil,
			value:    val,
		}
		f.flags = append(f.flags, fl)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	result := make([]feature, 0, len(featureOrder))
	for _, id := range featureOrder {
		result = append(result, *featureMap[id])
	}
	return result, nil
}

func unmarshalValue(b []byte) (*pbflagsv1.FlagValue, error) {
	if len(b) == 0 {
		return nil, nil
	}
	v := &pbflagsv1.FlagValue{}
	if err := proto.Unmarshal(b, v); err != nil {
		return nil, err
	}
	return v, nil
}

// yamlConfig matches the YAML structure expected by configfile.Parse.
type yamlConfig struct {
	Feature string               `yaml:"feature"`
	Flags   map[string]yamlEntry `yaml:"flags"`
}

type yamlEntry struct {
	Value      any             `yaml:"value,omitempty"`
	Conditions []yamlCondition `yaml:"conditions,omitempty"`
}

type yamlCondition struct {
	When      string `yaml:"when,omitempty"`
	Otherwise any    `yaml:"otherwise,omitempty"`
	Value     any    `yaml:"value,omitempty"`
}

func generateYAML(f feature, opts Options) ([]byte, error) {
	cfg := yamlConfig{
		Feature: f.id,
		Flags:   make(map[string]yamlEntry, len(f.flags)),
	}

	for _, fl := range f.flags {
		entry, err := buildFlagEntry(fl, opts)
		if err != nil {
			return nil, fmt.Errorf("flag %q: %w", fl.name, err)
		}
		cfg.Flags[fl.name] = entry
	}

	var b strings.Builder
	b.WriteString("# Generated by: pbflags config export\n")
	fmt.Fprintf(&b, "# Feature: %s\n", f.id)
	b.WriteString("# Review and commit to your config directory.\n\n")

	data, err := yaml.Marshal(cfg)
	if err != nil {
		return nil, err
	}
	b.Write(data)
	return []byte(b.String()), nil
}

func buildFlagEntry(fl flag, _ Options) (yamlEntry, error) {
	val, err := flagfmt.AsAny(fl.value)
	if err != nil {
		return yamlEntry{}, err
	}
	if val == nil {
		val = typedZero(fl.flagType)
	}
	return yamlEntry{Value: val}, nil
}

func typedZero(flagType string) any {
	switch flagType {
	case "BOOL":
		return false
	case "STRING":
		return ""
	case "INT64":
		return int64(0)
	case "DOUBLE":
		return float64(0)
	case "BOOL_LIST":
		return []bool{}
	case "STRING_LIST":
		return []string{}
	case "INT64_LIST":
		return []int64{}
	case "DOUBLE_LIST":
		return []float64{}
	default:
		return nil
	}
}
