// Code generated by protoc-gen-pbflags. DO NOT EDIT.
package org.spotlightgov.pbflags.generated;

import org.spotlightgov.pbflags.Dimension;

/** Generated typed dimension constructors for the EvaluationContext. */
public final class Dimensions {

  private Dimensions() {}

  /** Sets the user_id dimension (Authenticated user identifier). */
  public static Dimension userId(String v) {
    return Dimension.ofString("user_id", v);
  }

  /** Sets the session_id dimension (Browser session (unauthenticated users)). */
  public static Dimension sessionId(String v) {
    return Dimension.ofString("session_id", v);
  }

  /** Sets the plan dimension (Subscription tier). */
  public static Dimension plan(org.spotlightgov.pbflags.example.proto.PlanLevel v) {
    return Dimension.ofEnum("plan", v.getValueDescriptor());
  }

  /** Sets the device_type dimension (Client device class). */
  public static Dimension deviceType(org.spotlightgov.pbflags.example.proto.DeviceType v) {
    return Dimension.ofEnum("device_type", v.getValueDescriptor());
  }

  /** Sets the is_internal dimension (Internal employee). */
  public static Dimension isInternal(boolean v) {
    return Dimension.ofBool("is_internal", v);
  }
}
