// Code generated by protoc-gen-pbflags. DO NOT EDIT.
package org.spotlightgov.pbflags.generated;

import dagger.Module;
import dagger.Provides;
import org.spotlightgov.pbflags.FlagEvaluator;
import org.spotlightgov.pbflags.ScopedEvaluator;

/**
 * Dagger module providing the request-scoped {@link FlagEvaluator}.
 *
 * <p>Bind dimensions in request middleware via {@link ScopedEvaluator#bind}, then inject
 * {@link FlagEvaluator} into request-scoped components.
 */
@Module
public final class ScopedEvaluatorModule {

  @Provides
  static FlagEvaluator provideScopedEvaluator() {
    return ScopedEvaluator.current();
  }
}
