// Code generated by protoc-gen-pbflags. DO NOT EDIT.
package org.spotlightgov.pbflags.generated;

import java.util.List;
import org.spotlightgov.pbflags.Flag;
import org.spotlightgov.pbflags.ListFlag;

/**
 * Mutable test stub for {@link NotificationsFlags}.
 *
 * <p>Each flag accessor delegates to its corresponding field, which is pre-populated with the
 * compiled default. Override individual flags via the fluent setters.
 */
public final class TestNotificationsFlags implements NotificationsFlags {

  private Flag<Boolean> emailEnabledFn = () -> EMAIL_ENABLED_DEFAULT;
  private Flag<String> digestFrequencyFn = () -> DIGEST_FREQUENCY_DEFAULT;
  private Flag<Long> maxRetriesFn = () -> MAX_RETRIES_DEFAULT;
  private Flag<Double> scoreThresholdFn = () -> SCORE_THRESHOLD_DEFAULT;
  private ListFlag<String> notificationEmailsFn = () -> NOTIFICATION_EMAILS_DEFAULT;
  private ListFlag<Long> retryDelaysFn = () -> RETRY_DELAYS_DEFAULT;

  /** Override {@code emailEnabled()} to return the given value. */
  public TestNotificationsFlags emailEnabled(boolean value) {
    this.emailEnabledFn = () -> value;
    return this;
  }

  /** Override {@code digestFrequency()} to return the given value. */
  public TestNotificationsFlags digestFrequency(String value) {
    this.digestFrequencyFn = () -> value;
    return this;
  }

  /** Override {@code maxRetries()} to return the given value. */
  public TestNotificationsFlags maxRetries(long value) {
    this.maxRetriesFn = () -> value;
    return this;
  }

  /** Override {@code scoreThreshold()} to return the given value. */
  public TestNotificationsFlags scoreThreshold(double value) {
    this.scoreThresholdFn = () -> value;
    return this;
  }

  /** Override {@code notificationEmails()} to return the given value. */
  public TestNotificationsFlags notificationEmails(List<String> value) {
    this.notificationEmailsFn = () -> value;
    return this;
  }

  /** Override {@code retryDelays()} to return the given value. */
  public TestNotificationsFlags retryDelays(List<Long> value) {
    this.retryDelaysFn = () -> value;
    return this;
  }

  @Override
  public Flag<Boolean> emailEnabled() {
    return emailEnabledFn;
  }

  @Override
  public Flag<String> digestFrequency() {
    return digestFrequencyFn;
  }

  @Override
  public Flag<Long> maxRetries() {
    return maxRetriesFn;
  }

  @Override
  public Flag<Double> scoreThreshold() {
    return scoreThresholdFn;
  }

  @Override
  public ListFlag<String> notificationEmails() {
    return notificationEmailsFn;
  }

  @Override
  public ListFlag<Long> retryDelays() {
    return retryDelaysFn;
  }

}
