// Code generated by protoc-gen-pbflags. DO NOT EDIT.

package dims

import (
	context "context"
	notificationsflags "github.com/SpotlightGOV/pbflags/gen/flags/notificationsflags"
	pbflags "github.com/SpotlightGOV/pbflags/pbflags"
)

// HasNotifications is a duck-typed interface for scopes that provide notifications flags.
type HasNotifications interface {
	Notifications() notificationsflags.NotificationsFlags
}

// AnonFeatures provides feature flag access for the anon evaluation scope.
type AnonFeatures struct {
	eval                pbflags.Evaluator
	sessionID           string
	cachedNotifications notificationsflags.NotificationsFlags
}

// NewAnonFeatures creates a AnonFeatures with the given evaluator and dimensions.
func NewAnonFeatures(eval pbflags.Evaluator, sessionID string) *AnonFeatures {
	return &AnonFeatures{
		eval:      eval,
		sessionID: sessionID,
	}
}

type anonFeaturesKey struct{}

// ContextWithAnonFeatures stores the features in a context.Context.
func ContextWithAnonFeatures(ctx context.Context, f *AnonFeatures) context.Context {
	return context.WithValue(ctx, anonFeaturesKey{}, f)
}

// AnonFeaturesFrom retrieves the features from a context.Context.
func AnonFeaturesFrom(ctx context.Context) *AnonFeatures {
	v, _ := ctx.Value(anonFeaturesKey{}).(*AnonFeatures)
	return v
}

// Notifications returns a notifications flags client scoped to this evaluation context.
func (f *AnonFeatures) Notifications() notificationsflags.NotificationsFlags {
	if f.cachedNotifications == nil {
		eval := f.eval
		eval = eval.With(SessionID(f.sessionID))
		f.cachedNotifications = notificationsflags.New(eval)
	}
	return f.cachedNotifications
}

// UserFeatures provides feature flag access for the user evaluation scope.
type UserFeatures struct {
	eval                pbflags.Evaluator
	sessionID           string
	userID              string
	cachedNotifications notificationsflags.NotificationsFlags
}

// NewUserFeatures creates a UserFeatures with the given evaluator and dimensions.
func NewUserFeatures(eval pbflags.Evaluator, sessionID string, userID string) *UserFeatures {
	return &UserFeatures{
		eval:      eval,
		sessionID: sessionID,
		userID:    userID,
	}
}

type userFeaturesKey struct{}

// ContextWithUserFeatures stores the features in a context.Context.
func ContextWithUserFeatures(ctx context.Context, f *UserFeatures) context.Context {
	return context.WithValue(ctx, userFeaturesKey{}, f)
}

// UserFeaturesFrom retrieves the features from a context.Context.
func UserFeaturesFrom(ctx context.Context) *UserFeatures {
	v, _ := ctx.Value(userFeaturesKey{}).(*UserFeatures)
	return v
}

// Notifications returns a notifications flags client scoped to this evaluation context.
func (f *UserFeatures) Notifications() notificationsflags.NotificationsFlags {
	if f.cachedNotifications == nil {
		eval := f.eval
		eval = eval.With(SessionID(f.sessionID))
		eval = eval.With(UserID(f.userID))
		f.cachedNotifications = notificationsflags.New(eval)
	}
	return f.cachedNotifications
}
